git-svn-id: https://scm.mvapich.cse.ohio-state.edu/svn/mpi/mvapich2/trunk@5945 09bc9535-d30e-0410-b1f7-d46b20a4725c

diff --git a/src/mpe2/sbin/mpeinstall.in b/src/mpe2/sbin/mpeinstall.in
--- a/src/mpe2/sbin/mpeinstall.in
+++ b/src/mpe2/sbin/mpeinstall.in
@@ -99,7 +99,7 @@ appendUninstall=0
 if [ -z "$UNINSTALLFILE" ] ; then
     INSTALL_base=`basename $0`
     UNINSTALL_base=`echo $INSTALL_base | sed -e 's/install/uninstall/'`
-    UNINSTALLFILE=${sbindir}/${UNINSTALL_base}
+    UNINSTALLFILE=$DESTDIR${sbindir}/${UNINSTALL_base}
 fi
 
 for arg in "$@" ; do
@@ -282,31 +282,33 @@ fi
 # Make the given directory.  This handles building intermediate directories
 # as required, and maintains a list of created directories in dirlist.
 MkDir() {
-dest=$DESTDIR$1
-if [ ! -d $dest ] ; then
+dest=$1
+if [ ! -d $DESTDIR$dest ] ; then
     dir=`echo $dest | sed 's%/% /%g'`
     path_to_date=''
     for path in $dir ; do
         path_to_date="$path_to_date$path"
-        if [ ! -d $path_to_date ] ; then
-            if [ $verbose = 1 ] ; then echo "Creating directory $dest" ; fi
-            $Show "mkdir $path_to_date"
+        if [ ! -d $DESTDIR$path_to_date ] ; then
+            if [ $verbose = 1 ] ; then
+                echo "Creating directory $DESTDIR$path_to_date"
+            fi
+            $Show "mkdir $DESTDIR$path_to_date"
             rc=$?
             if [ $rc != 0 ] ; then
-                echo "*** Error making directory $dest. ***"
+                echo "*** Error making directory $DESTDIR$path_to_date. ***"
                 errs=`expr $errs + 1`
                 if [ $failmode = "hard" ] ; then exit $rc ; fi
-                echo "Failed to create directory $path_to_date"
+                echo "Failed to create directory $DESTDIR$path_to_date"
                 exit 1
             else
                 # Note that we store in inverse order
-                dirlist="$1 $dirlist"
+                dirlist="$path_to_date $dirlist"
             fi
             if [ "X$DMODE" != "X" ] ; then
-                $Show chmod $DMODE $path_to_date
+                $Show chmod $DMODE $DESTDIR$path_to_date
                 rc=$?
                 if [ $rc != 0 ] ; then
-                    echo "*** Error setting mode to $DMODE on directory $path_to_date. ***"
+                    echo "*** Error setting mode to $DMODE on directory $DESTDIR$path_to_date. ***"
                     errs=`expr $errs + 1`
                     if [ $chmodfailmode = "hard" ] ; then exit $rc ; fi
                 fi
@@ -321,7 +323,7 @@ fi
 #
 # Fixup files with various xxxxbuild_dir to xxxxdir, install directory.
 #
-#   The MPE_CLINKER/MPE_FLINKER need to sync with mpe2/configure.in
+#   The MPE_CLINKER/MPE_FLINKER need to sync with mpe2/configure.ac
 #
 FixInstallFile() {
 if [ -d $DESTDIR$2 ] ; then
@@ -454,7 +456,7 @@ if [ "$prefix_override" = 1 -o "$package_override" = 1 ] ; then
         htmldir=${docdir}
     fi
     if [ $appendUninstall = 0 ] ; then
-        UNINSTALLFILE=${sbindir}/${UNINSTALL_base}
+        UNINSTALLFILE=$DESTDIR${sbindir}/${UNINSTALL_base}
     fi
 fi
 
@@ -547,7 +549,7 @@ for pkg in logging graphics collchk ; do
     dirname=${pkg}_dirname
     eval dirvalue=\$"$dirname"
     if [ -f $libbuild_dir/../$dirvalue/Makefile ] ; then
-        examplesdir=$sharedir/examples_${pkg}
+        examplesdir=$sharedir/examples/${pkg}
         MkDir $examplesdir
 #       Install example C and Fortran programs
         InstallDirRecur $top_srcdir/$dirvalue $examplesdir
@@ -588,19 +590,19 @@ for type in doc man html ; do
 done
 
 # Remove old uninstall file
-if [ "$appendUninstall" = 0 -a -f $DESTDIR$UNINSTALLFILE ] ; then
-    $RM -f $DESTDIR$UNINSTALLFILE
+if [ "$appendUninstall" = 0 -a -f $UNINSTALLFILE ] ; then
+    $RM -f $UNINSTALLFILE
 fi
 #
 # Open an uninstall file and force strong echo if one does NOT exist
-if [ ! -f $DESTDIR$UNINSTALLFILE ] ; then
-    cat > $DESTDIR$UNINSTALLFILE <<EOF
+if [ ! -f $UNINSTALLFILE ] ; then
+    cat > $UNINSTALLFILE <<EOF
 #! /bin/sh
 set -x
 EOF
 fi
 
-chmod u+x $DESTDIR$UNINSTALLFILE
+chmod u+x $UNINSTALLFILE
 
 # Install the SLOG-2 tools if they exist
 # Don't set the prefix if the default is chosen.
@@ -619,29 +621,33 @@ fi
 #  Clean up the example directories
 for pkg in logging graphics ; do
     dirname=${pkg}_dirname
-    examplesdir=$sharedir/examples_${pkg}
+    examplesdir=$sharedir/examples/${pkg}
     if [ -s $DESTDIR$examplesdir/Makefile ] ; then
-       echo "( cd $examplesdir && $MAKE clean )" >> $DESTDIR$UNINSTALLFILE
+       echo "( cd \${DESTDIR}$examplesdir && $MAKE clean )" >> $UNINSTALLFILE
     fi
 done
 
 # Add the files to be removed to the UNINSTALLFILE
 for file in $filelist ; do
-    echo "$RM -f $file" >> $DESTDIR$UNINSTALLFILE
+    echo "$RM -f \${DESTDIR}$file" >> $UNINSTALLFILE
 done
 
 if [ "$appendUninstall" = 0 ] ; then
-    echo "$RM -f $sbindir/mpeuninstall" >> $DESTDIR$UNINSTALLFILE
-    echo "$RM -f $UNINSTALLFILE" >> $DESTDIR$UNINSTALLFILE
+    if [ -n "${DESTDIR}" ] ; then
+        uninstallfilename=`echo $UNINSTALLFILE| sed -e "s|^${DESTDIR}||g"`
+        echo "$RM -f \${DESTDIR}$uninstallfilename" >> $UNINSTALLFILE
+    else
+        echo "$RM -f \${DESTDIR}$UNINSTALLFILE" >> $UNINSTALLFILE
+    fi
 fi
 
 # Add the directory removes to the UNINSTALL file
 for dir in $dirlist ; do
-    echo "if [ -d $dir ] ; then rmdir $dir ; fi" >> $DESTDIR$UNINSTALLFILE
+    echo "if [ -d \${DESTDIR}$dir ] ; then rmdir \${DESTDIR}$dir || true ; fi" >> $UNINSTALLFILE
 done
 
 if [ "$appendUninstall" = 0 ] ; then
-    cp $DESTDIR$UNINSTALLFILE $DESTDIR$sbinbuild_dir/mpeuninstall
+    cp $UNINSTALLFILE $sbinbuild_dir/mpeuninstall
 #
     echo "Installed $pkgname in $DESTDIR$prefix"
     echo "$UNINSTALLFILE may be used to remove the installation"
