git-svn-id: https://scm.mvapich.cse.ohio-state.edu/svn/mpi/mvapich2/trunk@4600 09bc9535-d30e-0410-b1f7-d46b20a4725c

diff --git a/src/mpid/ch3/channels/sock/builddll b/src/mpid/ch3/channels/sock/builddll
--- a/src/mpid/ch3/channels/sock/builddll
+++ b/src/mpid/ch3/channels/sock/builddll
@@ -1,6 +1,7 @@
 #! /bin/sh
 #
 set -x
+printenv
 # This script builds a stand-alone DLL for the socket channel.
 # It makes use of the configure scripts in the necessary components
 #
@@ -10,6 +11,7 @@ mypath=`echo $mypath | sed -e 's/builddll//'`
 mympich2=`(cd $mypath && cd ../../../../.. && pwd)`
 mybuild=`(cd ../../../../../ && pwd)`
 #
+echo "Building channel dll for sock with $0"
 # Get the prefix, libdir, and exec_prefix, which may be needed for
 # setting installation directories.  These may be either passed on the
 # command line or as environment variables
@@ -35,6 +37,12 @@ for arg do
 done
 BUILD_DLLS=yes
 export BUILD_DLLS
+#
+# We must have a valid ABIVERSION
+if [ "X$ABIVERSION" = "X" ] ; then
+    echo "No ABIVERSION available - required to build sock DLL"
+    exit 1
+fi
 #
 # Determine shared library type (only a few supported)
 osname=`uname -s`
@@ -80,10 +88,9 @@ export CC_SHL
 export C_LINK_SHL
 export SHLIB_EXT
 #
-MPICH2_INCLUDE_FLAGS=-I$mympich2/src/mpid/ch3/include
-MPICH2_INCLUDE_FLAGS="$MPICH2_INCLUDE_FLAGS -I$mympich2/src/mpid/ch3/util/sock"
-MPICH2_INCLUDE_FLAGS="$MPICH2_INCLUDE_FLAGS -I$mybuild/src/mpid/ch3/util/sock"
-export MPICH2_INCLUDE_FLAGS
+CPPFLAGS="$CPPFLAGS -I$mympich2/src/mpid/ch3/include"
+CPPFLAGS="$CPPFLAGS -I$mympich2/src/mpid/ch3/util/sock"
+CPPFLAGS="$CPPFLAGS -I$mybuild/src/mpid/ch3/util/sock"
 
 # The sock channel requires the sock utilities in mpid/common/sock
 # This directory may not exist yet (no other configure may have 
@@ -100,15 +107,17 @@ if [ $? != 0 ] ; then
     exit 1
 fi
 
-( MPICH2_INCLUDE_FLAGS="$MPICH2_INCLUDE_FLAGS -I$mympich2/src/mpid/common/datatype" ; \
-MPICH2_INCLUDE_FLAGS="$MPICH2_INCLUDE_FLAGS -I$mympich2/src/mpid/common/sock" ; \
-MPICH2_INCLUDE_FLAGS="$MPICH2_INCLUDE_FLAGS -I$mympich2/src/mpid/common/sock/poll" ; \
-MPICH2_INCLUDE_FLAGS="$MPICH2_INCLUDE_FLAGS -I../../../../common/sock" ; \
-MPICH2_INCLUDE_FLAGS="$MPICH2_INCLUDE_FLAGS -I../../../../common/sock/poll" ; \
-MPICH2_INCLUDE_FLAGS="$MPICH2_INCLUDE_FLAGS -I../include" ; \
-MPICH2_INCLUDE_FLAGS="$MPICH2_INCLUDE_FLAGS -I../../../include" ; \
-MPICH2_INCLUDE_FLAGS="$MPICH2_INCLUDE_FLAGS -I$mympich2/src/mpid/ch3/channels/sock/include" ; \
-export MPICH2_INCLUDE_FLAGS ; \
+# Ensure that the sock channel includes are found before the dllchan includes
+(\
+CPPFLAGS="-I../../channels/sock/include -I$mympich2/src/mpid/ch3/channels/sock/include $CPPFLAGS";\
+CPPFLAGS="$CPPFLAGS -I$mympich2/src/mpid/common/datatype" ; \
+CPPFLAGS="$CPPFLAGS -I$mympich2/src/mpid/common/sock" ; \
+CPPFLAGS="$CPPFLAGS -I$mympich2/src/mpid/common/sock/poll" ; \
+CPPFLAGS="$CPPFLAGS -I../../../../common/sock" ; \
+CPPFLAGS="$CPPFLAGS -I../../../../common/sock/poll" ; \
+CPPFLAGS="$CPPFLAGS -I../include" ; \
+CPPFLAGS="$CPPFLAGS -I../../../include" ; \
+CPPFLAGS="$CPPFLAGS -I$mympich2/src/mpid/ch3/channels/sock/include" ; \
  $mypath/configure --enable-sharedlibs=$shlibtype \
     --prefix=$prefix --libdir=$libdir --exec-prefix=$exec_prefix )
 #
@@ -150,15 +159,16 @@ if [ ! -d ../../util/sock ] ; then
 fi
 
 (\
-MPICH2_INCLUDE_FLAGS="$MPICH2_INCLUDE_FLAGS -I$mympich2/src/mpid/common/sock" ; \
-MPICH2_INCLUDE_FLAGS="$MPICH2_INCLUDE_FLAGS -I$mympich2/src/mpid/common/sock/poll" ; \
-MPICH2_INCLUDE_FLAGS="$MPICH2_INCLUDE_FLAGS -I../../../common/sock" ; \
-MPICH2_INCLUDE_FLAGS="$MPICH2_INCLUDE_FLAGS -I../../../common/sock/poll" ; \
-MPICH2_INCLUDE_FLAGS="$MPICH2_INCLUDE_FLAGS -I../../channels/sock/include" ; \
-MPICH2_INCLUDE_FLAGS="$MPICH2_INCLUDE_FLAGS -I$mympich2/src/mpid/ch3/channels/sock/include" ; \
-MPICH2_INCLUDE_FLAGS="$MPICH2_INCLUDE_FLAGS -I../../include" ; \
-MPICH2_INCLUDE_FLAGS="$MPICH2_INCLUDE_FLAGS -I$mympich2/src/mpid/ch3/include" ; \
-MPICH2_INCLUDE_FLAGS="$MPICH2_INCLUDE_FLAGS -I$mympich2/src/mpid/common/datatype" ; \
+CPPFLAGS="-I../../channels/sock/include -I$mympich2/src/mpid/ch3/channels/sock/include $CPPFLAGS";\
+CPPFLAGS="$CPPFLAGS -I$mympich2/src/mpid/common/sock" ; \
+CPPFLAGS="$CPPFLAGS -I$mympich2/src/mpid/common/sock/poll" ; \
+CPPFLAGS="$CPPFLAGS -I../../../common/sock" ; \
+CPPFLAGS="$CPPFLAGS -I../../../common/sock/poll" ; \
+CPPFLAGS="$CPPFLAGS -I../../channels/sock/include" ; \
+CPPFLAGS="$CPPFLAGS -I$mympich2/src/mpid/ch3/channels/sock/include" ; \
+CPPFLAGS="$CPPFLAGS -I../../include" ; \
+CPPFLAGS="$CPPFLAGS -I$mympich2/src/mpid/ch3/include" ; \
+CPPFLAGS="$CPPFLAGS -I$mympich2/src/mpid/common/datatype" ; \
 cd ../../util/sock && \
     $mympich2/src/mpid/ch3/util/sock/configure --enable-sharedlibs=$shlibtype \
     --prefix=$prefix --libdir=$libdir --exec-prefix=$exec_prefix )
@@ -179,10 +189,11 @@ cd ..
 rm -rf .tmp
 #
 # Now, create the dynamically-loadable library
+# Some of the routines now depend on routines in libmpl.
 rm -f libmpich2-ch3-sock*.dylib libmpich2-ch3-sock*.so
 $mybuild/src/util/createshlib -echo --mode=link -version-info "1:1" \
     -clink="$C_LINK_SHL" -cc=gcc -libtype=$shlibtype \
-    -o libmpich2-ch3-sock.la -rpath `pwd`
+    -o libmpich2-ch3-sock.la -rpath `pwd` -L../../../../../lib -lmpl 
 rc=$?
 if [ $rc != 0 ] ; then 
     echo "Createshlib step failed for sock channel"
