git-svn-id: https://scm.mvapich.cse.ohio-state.edu/svn/mpi/mvapich2/trunk@1419 09bc9535-d30e-0410-b1f7-d46b20a4725c

diff --git a/maint/updatefiles b/maint/updatefiles
--- a/maint/updatefiles
+++ b/maint/updatefiles
@@ -1,4 +1,7 @@
 #! /bin/sh
+# 
+# (C) 2006 by Argonne National Laboratory.
+#     See COPYRIGHT in top-level directory.
 #
 # Update all of the derived files
 # For best performance, execute this in the top-level directory.
@@ -9,6 +12,11 @@
 # mpich tree.  This is not yet implemented.
 error_summary=""
 acVersion=unknown
+# confdbSrcDir is used for checkouts that were not able to checkout 
+# confdb because they're not members of the Unix group that includes that
+# directory.
+confdbSrcDir=/homes/MPI/testing/mpich2/mpich2/confdb
+#
 # finalStatus records whether there have been problems in updatefiles
 # 1 = warning, 3 = fatal, 2 = reserved for future use, 
 # 0 = no problems detected.
@@ -28,10 +36,15 @@ do_f77tof90=yes
 do_build_configure=yes
 do_genstates=yes
 do_makefiles=yes
+do_smpdversion=yes
+
+# Allow MAKE to be set from the environment
+MAKE=${MAKE-make}
+
 
 # List of steps that we will consider
 # (We do not include depend because the values for depend are not just yes/no)
-AllSteps="geterrmsgs bindings f77 f77tof90 build_configure genstates makefiles"
+AllSteps="geterrmsgs bindings f77 f77tof90 build_configure genstates makefiles smpdversion"
 stepsCleared=no
 
 # Options for some steps
@@ -47,24 +60,27 @@ for arg in "$@" ; do
 	;;
 	
     -do=*)
-    if [ $stepsCleared = no ] ; then
-	for step in $AllSteps ; do
-	    var=do_$step
-	    eval $var=no
-	done
-	stepsCleared=yes
-    fi
     opt=`echo A$arg | sed -e 's/A-do=//'`
-    # Handle some synonym
+    # Handle some synonyms
     case $opt in 
 	build-configure|configure) opt=build_configure ;;
 	makefile|Makefile|Makefiles) opt=makefiles;;
     esac
     var=do_$opt
-    eval oldval=$"$var"
+    # Check that this opt is known
+    eval oldval=\$"$var"
     if [ -z "$oldval" ] ; then
 	echo "-do=$opt is unrecognized"
+	exit 1
     else 
+        if [ $stepsCleared = no ] ; then
+	    for step in $AllSteps ; do
+	        var=do_$step
+	        eval $var=no
+	    done
+	    stepsCleared=yes
+        fi
+        var=do_$opt
         eval $var=yes
     fi
     ;;
@@ -270,7 +286,10 @@ if [ $do_geterrmsgs = "yes" ] ; then
         echo "Extracting the error messages..."
         rm -rf .tmp
         rm -f .err
-        maint/extracterrmsgs -skip=src/util/multichannel/mpi.c `cat maint/errmsgdirs` > .tmp 2>.err
+	rm -f unusederr.txt
+        maint/extracterrmsgs -careful=unusederr.txt \
+	    -skip=src/util/multichannel/mpi.c `cat maint/errmsgdirs` > \
+	    .tmp 2>.err
         # (error here is ok)
         update_errdefs=yes
         if [ -s .err ] ; then 
@@ -291,6 +310,10 @@ Error message files in src/mpi/errhan were not updated."
             # Incase it exists but has zero size
             rm -f .err
         fi
+	if [ -s unusederr.txt ] ; then
+	    echo "There are unused error message texts in src/mpi/errhan/errnames.txt"
+	    echo "See the file unusederr.txt for the complete list"
+        fi
         if [ -s .tmp -a "$update_errdefs" = "yes" ] ; then
             mv .tmp src/mpi/errhan/defmsg.h
         fi
@@ -302,6 +325,8 @@ static const int generic_msgs_len = 0;
 static msgpair generic_err_msgs[] = { {0xacebad03, 0, "no error catalog", 0xcb0bfa11}, };
 static const int specific_msgs_len = 0;
 static msgpair specific_err_msgs[] = {  {0xacebad03,0,0,0xcb0bfa11}, };
+#if MPICH_ERROR_MSG_LEVEL > MPICH_ERROR_MSG_NONE
+#define MPIR_MAX_ERROR_CLASS_INDEX 54
 static int class_to_index[] = {
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
@@ -309,6 +334,7 @@ static int class_to_index[] = {
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0 };
+#endif
 EOF
         fi
     fi
@@ -367,9 +393,13 @@ fi
 
 # Run some of the simple codes
 #
-if [ -x maint/genstates -a $do_genstates = "yes" ] ; then
+# if [ -x maint/genstates -a $do_genstates = "yes" ] ; then
+#     echo "Creating the enumeration of logging states into src/include/mpiallstates.h"
+#     maint/genstates
+# fi
+if [ -x maint/extractstates -a $do_genstates = "yes" ] ; then
     echo "Creating the enumeration of logging states into src/include/mpiallstates.h"
-    maint/genstates
+    maint/extractstates
 fi
 # Create and/or update the f90 tests
 if [ -x maint/f77tof90 -a $do_f77tof90 = "yes" ] ; then
@@ -468,8 +498,26 @@ if [ $do_build_configure = yes ] ; then
         # Before we try to rebuild any configure steps, make sure that 
         # we have the necessary macro definitions
         if [ ! -d confdb -o ! -s confdb/aclocal.m4 ] ; then
-	    echo "Directory `pwd`/confdb is missing and is required for rebuilding configure"
-  	    exit 1
+	    # See if we can export a copy of confdb
+	    if [ -d $confdbSrcDir ] ; then
+                cp -rp $confdbSrcDir confdb
+                # Remove the CVS directories
+		if test -d confdb/CVS ; then
+                    (cd confdb && find . -name CVS -print | xargs rm -rf)
+                fi
+            else
+                echo "Directory `pwd`/confdb is missing and is required for rebuilding configure"
+  	        exit 1
+            fi
+        elif [ -d confdb -a -d "$confdbSrcDir" -a ! -d confdb/CVS ] ; then
+            # This is a copy; get an up-to-date copy.  We only do 
+	    # this if there is an alternate source, in case this is
+	    # part of the distributed version and not local.
+            cp -rp $confdbSrcDir confdb
+            # Remove the CVS directories
+	    if test -d confdb/CVS ; then
+                (cd confdb && find . -name CVS -print | xargs rm -rf)
+            fi
         fi
 	# Check for out-of-date configures (the dependency handling
 	# isn't 100% accurate, so we use this step as an additional
@@ -479,7 +527,13 @@ if [ $do_build_configure = yes ] ; then
 	    find . -name configure -print | grep -v maint/configure | xargs rm -f
 	    # If we don't delete the autom4te.cache files, bugs in 
 	    # autoconf may fail to correctly update configure
-	    find . -name autom4te.cache | xargs -r rm -f
+	    # Gah. Some xargs don't accept -r, other break if there is no
+	    # input.  To avoid that, we do this in two steps: first the
+	    # find, then the rm (if there are any files)
+	    rm -f .atmp
+	    find . -name autom4te.cache > .atmp 2>/dev/null
+	    if [ -s .atmp ] ; then xargs rm -f < .atmp ; fi
+	    rm -f .atmp
 	    date > maint/conftimestamp
 	else
 	    # We can't us a status check here because find will always
@@ -556,10 +610,10 @@ if [ $do_build_configure = yes ] ; then
 		        -e "s%@srcdir@%.%g" \
 		        -e '/include .*alldeps/d' \
 		        -e '/@SET_MAKE@/d' Makefile.in > mf.tmp ;\
-		        if make -q -f mf.tmp configure >mf.out 2>&1 ; then \
+		        if ${MAKE} -q -f mf.tmp configure >mf.out 2>&1 ; then \
                     : ; else \
 	            echo "Found $dir/configure.in; executing make configure target" ; \
-	            make -f mf.tmp configure ; fi ; rm -f mf.tmp  \
+	            ${MAKE} -f mf.tmp configure ; fi ; rm -f mf.tmp  \
 	            )
 		    # Newer versions of test support -nt, which is
 		    # filea newer-than fileb.  If this doesn't 
@@ -708,9 +762,10 @@ fi
 if [ $rm_prepost = yes ] ; then
     rm -f src/include/mpidpre.h src/include/mpidpost.h
 fi
-echo "Creating src/pm/smpd/smpd_version.h"
-smpdVersion=`cat maint/Version`
-cat >src/pm/smpd/smpd_version.h <<EOF
+if [ "$do_smpdversion" = yes ] ; then
+    echo "Creating src/pm/smpd/smpd_version.h"
+    smpdVersion=`cat maint/Version`
+    cat >src/pm/smpd/smpd_version.h <<EOF
 /* -*- Mode: C; c-basic-offset:4 ; -*- */
 /*  
  *  (C) 2005 by Argonne National Laboratory.
@@ -718,6 +773,7 @@ cat >src/pm/smpd/smpd_version.h <<EOF
  */
 #define SMPD_VERSION "$smpdVersion"
 EOF
+fi
 #
 # The following must be the last statements executed
 if [ -n "$error_summary" ] ; then
diff --git a/src/mpe2/sbin/mpeinstall.in b/src/mpe2/sbin/mpeinstall.in
--- a/src/mpe2/sbin/mpeinstall.in
+++ b/src/mpe2/sbin/mpeinstall.in
@@ -14,8 +14,6 @@
 # or different from the source directory
 #
 
-MAKE="@MAKE@"
-
 # Location of sources
 # top_srcdir=@top_srcdir@
 top_srcdir=@top_srcdir_abs@       # in absolute path
@@ -42,15 +40,25 @@ docdir=@docdir@
 
 # Assume PROF_LIBNAME=MPE_LIBNAME.
 PROF_LIBNAME=@MPE_LIBNAME@
-CPRP="@CPRP@"
-RM="@RM@"
-LN_S="@LN_S@"
 MPI_IMPL=@MPI_IMPL@
 MPE_BUILD_FORTRAN2C=@MPE_BUILD_FORTRAN2C@
+
+# Determine this package's name
+tmpname="`echo $top_srcdir | sed -e 's%\(.*\)/\([^/]*\)%\2%'`"
+pkgname="`echo $tmpname | sed -e 'y%abcdefghijklmnopqrstuvwxyz/%ABCDEFGHIJKLMNOPQRSTUVWXYZ_%'`"
+if [ "x$pkgname" = "x" ] ; then
+    pkgname="MPE2"
+fi
+
+MAKE="@MAKE@"
+INSTALL="@INSTALL@"
+RM="@RM@"
+LN_S="@LN_S@"
 
 # File access mode
 MODE=0644
 XMODE=0755
+DMODE=0755
 replace=1
 # set failmode to soft to let failures accumulate
 failmode="hard"
@@ -102,6 +110,9 @@ for arg in "$@" ; do
         -xmode=*) 
             XMODE=`echo $arg | sed -e 's/-xmode=//g'` 
             ;;
+        -dmode=*) 
+            DMODE=`echo $arg | sed -e 's/-dmode=//g'` 
+            ;;
         -t)
             Show=echo ; just_testing=1 ; failmode="soft"
             ;;
@@ -116,11 +127,12 @@ for arg in "$@" ; do
         -softchmod)               chmodfailmode="soft" ;;
         -help|-u|-usage|-h)
 cat <<EOF
-Install MPE into $prefix.
+Install $pkgname into $prefix.
 -prefix=path     - Destination directory.
 -uninstall=file  - File to append uninstall information to
 -mode=nnnn       - mode for regular files.  Default is $MODE .
--xmode=nnnn      - mode for execuables and directories.  Default is $XMODE .
+-xmode=nnnn      - mode for execuables.  Default is $XMODE .
+-dmode=nnnn      - mode for directories.  Default is $DMODE .
 -t               - Try only; do no installation.
 -manpath=path    - Set an alternate path for the man pages
 -noman           - Do not install the man pages.
@@ -154,12 +166,9 @@ fi
 #
 ##############################################################################
 
-# We could use install, but install is too different and too hard to 
-# test.  So here are the routines to copy file, make directories, and 
-# replace #...# and @...@ in files
-CP=cp
+INSTALLER="$INSTALL"
 #
-CopyFile() {
+InstallFile() {
 if [ -z "$3" ] ; then
     mode=$MODE
 else
@@ -175,69 +184,58 @@ fi
 if [ $replace = 0 -a -f $dest ] ; then
     if [ $verbose = 1 ] ; then echo "$dest exists; not changed" ; fi
 elif [ -d $1 ] ; then
-    echo ">>> $1 is a directory; not copied <<<"
+    echo ">>> $1 is a directory; not installed <<<"
     errs=`expr $errs + 1`
     if [ $failmode = "hard" ] ; then exit 1 ; fi
 elif [ ! -f $1 ] ; then 
-    echo "**File $1 does not exist (or is not a regular file)!"
+    echo "*** File $1 does not exist (or is not a regular file)! ***"
     errs=`expr $errs + 1`
     if [ $failmode = "hard" ] ; then exit 1 ; fi
 elif [ "$1" = "$dest" ] ; then
-    echo "**File $1 is being copied to itself!"
+    echo "*** File $1 is being installed to itself! ***"
     errs=`expr $errs + 1`
     if [ $failmode = "hard" ] ; then exit 1 ; fi
 else
-    if [ $verbose = 1 ] ; then echo "Copying $1 to $dest" ; fi
+    if [ $verbose = 1 ] ; then echo "Installing $1 to $dest" ; fi
     if [ -f $dest ] ; then
         echo "Replacing existing file $dest..."
         $Show $RM -f $dest
     fi
-    $Show $CP $1 $dest
+    if [ "X$mode" != "X" ] ; then
+        $Show $INSTALLER -m $mode $1 $dest
+    else
+        $Show $INSTALLER $1 $dest
+    fi
     rc=$?
     if [ $rc != 0 ] ; then
-        echo "**Error copying file $1 to $dest **"
+        echo "*** Error installing file $1 to $dest with mode $mode. ***"
         errs=`expr $errs + 1`
         if [ $failmode = "hard" ] ; then exit $rc ; fi
     else
-        # store the destination filename copied
+        # store the destination installed filename
         filelist="$filelist $destfile"
-    fi
-    $Show chmod $mode $dest
-    rc=$?
-    if [ $rc != 0 ] ; then
-        echo "**Error setting mode to $mode on file $dest**"
-        errs=`expr $errs + 1`
-        if [ $chmodefailmode = "hard" ] ; then exit $rc ; fi
     fi
 fi
 }
 
 
-#
-# A version of copy file that preserves file dates
-CopyFileP() {
-    CP="$CPRP -p"
-    CopyFile $1 $2 $3
-    CP=cp
-}
-
 
 #
-# A version of recursive directory copy that copies or replaces files
-# ( file replacement of replace=1 ) and reserves copied file dates
-# but does NOT copy directories, CVS/, old/ and tex/.
+# Recursive directory install that installs or replaces files
+# (file replacement of replace=1) but excluding directories,
+# CVS/, old/ and tex/.
 # $1 is the src directory, $2 is dest directory, $3 is $MODE or $XMODE
-CopyDirRecurP() {
+InstallDirRecur() {
 if [ -n "$1" -a -n "$2" ] ; then
     if [ -d $1 ] ; then
         MkDir $2
         # use $4 as a local variable
         # & set it as the original PWD before "cd $1"
-        set $1 $2 ${3:-$MODE} `pwd`
+        set $1 $2 ${3:-"$MODE"} `pwd`
         cd $1
         for file in * ; do
             if [ -f $file ] ; then
-                CopyFileP $file $2/$file $3
+                InstallFile $file $2/$file $3
             fi
         done
         for dir in * ; do
@@ -245,7 +243,7 @@ if [ -n "$1" -a -n "$2" ] ; then
                  -a "$dir" != "CVS" -a "$dir" != "old" \
                  -a "$dir" != "tex" \
                ] ; then
-                CopyDirRecurP $dir $2/$dir $3
+                InstallDirRecur $dir $2/$dir $3
             fi
         done
         # cd back where it comes from
@@ -273,7 +271,7 @@ if [ ! -d $dest ] ; then
             $Show "mkdir $path_to_date"
             rc=$?
             if [ $rc != 0 ] ; then
-                echo "**Error making directory $dest**"
+                echo "*** Error making directory $dest. ***"
                 errs=`expr $errs + 1`
                 if [ $failmode = "hard" ] ; then exit $rc ; fi
                 echo "Failed to create directory $path_to_date"
@@ -282,12 +280,14 @@ if [ ! -d $dest ] ; then
                 # Note that we store in inverse order
                 dirlist="$1 $dirlist"
             fi
-            $Show chmod $XMODE $path_to_date
-            rc=$?
-            if [ $rc != 0 ] ; then
-                echo "**Error setting mode to $XMODE on directory $path_to_date**"
-                errs=`expr $errs + 1`
-                if [ $chmodfailmode = "hard" ] ; then exit $rc ; fi
+            if [ "X$DMODE" != "X" ] ; then
+                $Show chmod $DMODE $path_to_date
+                rc=$?
+                if [ $rc != 0 ] ; then
+                    echo "*** Error setting mode to $DMODE on directory $path_to_date. ***"
+                    errs=`expr $errs + 1`
+                    if [ $chmodfailmode = "hard" ] ; then exit $rc ; fi
+                fi
             fi
         fi
     done
@@ -310,7 +310,7 @@ fi
 if [ $replace = 0 -a -f $dest ] ; then
     if [ $verbose = 1 ] ; then echo "$dest exists; not changed" ; fi
 elif [ -d $1 ] ; then
-    echo "$1 is a directory; not copied"
+    echo "$1 is a directory; not fixed"
 else
     if [ -f $dest ] ; then $Show $RM -f $dest ; fi
     if [ $just_testing = 0 ] ; then \
@@ -320,26 +320,30 @@ else
             -e "s%^MPI_F77\([ ]*\)=\([ ]*\).*\$%MPI_F77\1=\2$bindir/mpif77%g" \
             -e "s%^MPE_INCDIR\([ ]*\)=\([ ]*\).*\$%MPE_INCDIR\1=\2$includedir%g" \
             -e "s%^MPE_LIBDIR\([ ]*\)=\([ ]*\).*\$%MPE_LIBDIR\1=\2$libdir%g" \
+            -e "s%^MPE_BINDIR\([ ]*\)=\([ ]*\).*\$%MPE_BINDIR\1=\2$bindir%g" \
             -e "s%^MPE_ETCDIR\([ ]*\)=\([ ]*\).*\$%MPE_ETCDIR\1=\2$sysconfdir%g" \
+            -e "s%^MPE_SBINDIR\([ ]*\)=\([ ]*\).*\$%MPE_SBINDIR\1=\2$sbindir%g" \
             $1 > $dest
         else
             sed \
             -e "s%^MPE_INCDIR\([ ]*\)=\([ ]*\).*\$%MPE_INCDIR\1=\2$includedir%g" \
             -e "s%^MPE_LIBDIR\([ ]*\)=\([ ]*\).*\$%MPE_LIBDIR\1=\2$libdir%g" \
+            -e "s%^MPE_BINDIR\([ ]*\)=\([ ]*\).*\$%MPE_BINDIR\1=\2$bindir%g" \
             -e "s%^MPE_ETCDIR\([ ]*\)=\([ ]*\).*\$%MPE_ETCDIR\1=\2$sysconfdir%g" \
+            -e "s%^MPE_SBINDIR\([ ]*\)=\([ ]*\).*\$%MPE_SBINDIR\1=\2$sbindir%g" \
             $1 > $dest
         fi
         rc=$?
         if [ $rc != 0 ] ; then
-            echo "**** Error fixing up file $dest ****"
+            echo "*** Error fixing up file $dest. ***"
             errs=`expr $errs + 1`
             if [ $failmode = "hard" ] ; then exit $rc ; fi
         else
-            # store the destination filename fixed
+            # store the destination fixed filename
             filelist="$filelist $destfile"
         fi
     else
-        if [ $verbose = 1 ] ; then echo "Fixup $1 and copy to $dest" ; fi
+        if [ $verbose = 1 ] ; then echo "Fixup $1 and install to $dest" ; fi
     fi
 fi
 if [ -z "$3" ] ; then
@@ -347,12 +351,14 @@ if [ -z "$3" ] ; then
 else
     mode=$3
 fi
-$Show chmod $mode $dest
-rc=$?
-if [ $rc != 0 ] ; then
-    echo "**Error setting mode on file $dest**"
-    errs=`expr $errs + 1`
-    if [ $failmode = "hard" ] ; then exit $rc ; fi
+if [ "X$mode" != "X" ] ; then
+    $Show chmod $mode $dest
+    rc=$?
+    if [ $rc != 0 ] ; then
+        echo "*** Error setting mode $mode on file $dest. ***"
+        errs=`expr $errs + 1`
+        if [ $failmode = "hard" ] ; then exit $rc ; fi
+    fi
 fi
 }
 
@@ -363,7 +369,7 @@ fi
 #
 ##############################################################################
 if [ ! -s $libbuild_dir/lib${PROF_LIBNAME}.a ] ; then 
-    echo "You must make MPE before installing it!"
+    echo "You must make $pkgname before installing it!"
     echo "Could not find $libbuild_dir/lib${PROF_LIBNAME}.a !"
     exit 1
 fi
@@ -373,7 +379,7 @@ if [ ! -n "$prefix" ] ; then
     exit 1
 fi
 if [ $verbose = 1 ] ; then
-    echo "Install into $prefix"
+    echo "Install into $DESTDIR$prefix"
 fi
 
 if [ -d $DESTDIR$prefix ] ; then
@@ -412,57 +418,71 @@ if [ "$prefix_override" = 1 ] ; then
     fi
 fi
 
-# Copy end-user MPE include Files, i.e. mpe*h
+# Install end-user include Files, i.e. mpe*h
 if [ -n "$includebuild_dir" ] ; then
     if [ -d $includebuild_dir ] ; then
-        echo "Copying MPE include files to $DESTDIR$includedir"
+        echo "Installing $pkgname include files to $DESTDIR$includedir"
         if [ ! -d $DESTDIR$includedir ] ; then
             MkDir $includedir
         fi
         cd $includebuild_dir
         for file in clog*.h mpe*.h ; do
             if [ -f $includebuild_dir/$file ] ; then
-                CopyFileP $includebuild_dir/$file $includedir/$file $MODE
+                InstallFile $includebuild_dir/$file $includedir/$file $MODE
             fi
         done
     fi
 fi
 
-# Copy MPE libraries
+# Install libraries
 if [ -n "$libbuild_dir" ] ; then
     if [ -d $libbuild_dir ] ; then
-        echo "Copying MPE libraries to $DESTDIR$libdir"
-        CopyDirRecurP $libbuild_dir $libdir $MODE
+        echo "Installing $pkgname libraries to $DESTDIR$libdir"
+        InstallDirRecur $libbuild_dir $libdir $MODE
     fi
 fi
 
-# Copy MPE utility programs
+# Install utility programs
 if [ -n "$binbuild_dir" ] ; then
     if [ -d $binbuild_dir ] ; then
-         echo "Copying MPE utility programs to $DESTDIR$bindir"
-         CopyDirRecurP $binbuild_dir $bindir $XMODE
+         echo "Installing $pkgname utility programs to $DESTDIR$bindir"
+         InstallDirRecur $binbuild_dir $bindir $XMODE
          if [ -s $binbuild_dir/mpecc -a -x $binbuild_dir/mpecc ] ; then
-             FixInstallFile $binbuild_dir/mpecc $DESTDIR$bindir/mpecc $XMODE
+             FixInstallFile $binbuild_dir/mpecc $bindir/mpecc $XMODE
          fi
          if [ -s $binbuild_dir/mpefc -a -x $binbuild_dir/mpefc ] ; then
-             FixInstallFile $binbuild_dir/mpefc $DESTDIR$bindir/mpefc $XMODE
+             FixInstallFile $binbuild_dir/mpefc $bindir/mpefc $XMODE
          fi
     fi
 fi
 
-# Copy MPE compiler configuration files
+# Install compiler configuration files
 if [ -n "$etcbuild_dir" ] ; then
     if [ -d $etcbuild_dir ] ; then
-         echo "Copying MPE compiler configuration files to $DESTDIR$sysconfdir"
-         CopyDirRecurP $etcbuild_dir $sysconfdir $MODE
+         echo "Installing $pkgname configuration files to $DESTDIR$sysconfdir"
+         InstallDirRecur $etcbuild_dir $sysconfdir $MODE
          cd $etcbuild_dir && \
          for file in *.conf ; do \
-             FixInstallFile $file $DESTDIR$sysconfdir/$file ; \
+             FixInstallFile $file $sysconfdir/$file ; \
          done
     fi
 fi
 
+# Create $sbindir outside of nested IF blocks because $sbindir is needed
+# even if $sbinbuild_dir/* do not exist.
 MkDir $sbindir
+
+# Install system-admin related utilies
+if [ -n "$sbinbuild_dir" ] ; then
+    if [ -d $sbinbuild_dir ] ; then
+         echo "Installing $pkgname system utility programs to $DESTDIR$sbindir"
+         InstallFile    $sbinbuild_dir/mpecheckinstall  $sbindir $XMODE
+         FixInstallFile $sbinbuild_dir/mpetestlink      $sbindir $XMODE
+         FixInstallFile $sbinbuild_dir/mpetestexec      $sbindir $XMODE
+         FixInstallFile $sbinbuild_dir/mpetestexeclog   $sbindir $XMODE
+    fi
+fi
+
 MkDir $datadir
 
 # Set up Examples directory for the MPE Logging programs
@@ -475,10 +495,10 @@ for pkg in logging graphics collchk ; do
     if [ -f $libbuild_dir/../$dirvalue/Makefile ] ; then
         examplesdir=$datadir/examples_${pkg}
         MkDir $examplesdir
-#       Copy MPE Example C and Fortran programs
-        CopyDirRecurP $top_srcdir/$dirvalue $examplesdir
+#       Install example C and Fortran programs
+        InstallDirRecur $top_srcdir/$dirvalue $examplesdir
 
-#       Create MPE examples Makefile
+#       Create examples Makefile
         cd $DESTDIR$examplesdir && \
         FixInstallFile $libbuild_dir/../$dirvalue/Makefile \
                        $examplesdir/Makefile
@@ -499,10 +519,10 @@ for pkg in logging graphics collchk ; do
 done
 
 
-# Copy documentation related files if they exist,
-# ie CP $top_srcdir/doc  $docdir
-#    CP $top_srcdir/man  $mandir
-#    CP $top_srcdir/html $htmldir
+# Install documentation related files if they exist,
+# ie INSTALL $top_srcdir/doc  $docdir
+#    INSTALL $top_srcdir/man  $mandir
+#    INSTALL $top_srcdir/html $htmldir
 for type in doc man html ; do
     typename=${type}dir
     eval typevalue=\$"$typename"
@@ -510,8 +530,8 @@ for type in doc man html ; do
         if [ ! -d $DESTDIR$typevalue ] ; then
             MkDir $typevalue
         fi
-        echo "Copying MPE $type to $DESTDIR$typevalue"
-        CopyDirRecurP $top_srcdir/$type $typevalue $MODE
+        echo "Installing $pkgname $type to $DESTDIR$typevalue"
+        InstallDirRecur $top_srcdir/$type $typevalue $MODE
     fi
 done
 
@@ -533,15 +553,12 @@ chmod u+x $UNINSTALLFILE
 # Install the SLOG-2 tools if they exist
 # Don't set the prefix if the default is chosen.
 if [ -x $libbuild_dir/../src/slog2sdk/sbin/install-package ] ; then
-    if [ "$prefix_override" = "1" ] ; then
-        ( cd $libbuild_dir/../src/slog2sdk && \
-          ./sbin/install-package -prefix=$prefix -uninstall=$UNINSTALLFILE \
-                                 -mode=$MODE -xmode=$XMODE -copymode=core )
-    else
-        ( cd $libbuild_dir/../src/slog2sdk && \
-          ./sbin/install-package -uninstall=$UNINSTALLFILE \
-                                 -mode=$MODE -xmode=$XMODE -copymode=core )
+    install_opts="-mode=$MODE -xmode=$XMODE -dmode=$DMODE -copymode=core"
+    install_opts="-uninstall=$UNINSTALLFILE $install_opts"
+    if [ "$prefix_override" = 1 ] ; then
+        install_opts="-prefix=$prefix $install_opts"
     fi
+    ( cd $libbuild_dir/../src/slog2sdk && ./sbin/install-package $install_opts )
 fi
 
 #  Clean up the example directories
@@ -571,7 +588,7 @@ done
 if [ "$appendUninstall" = 0 ] ; then
     cp $UNINSTALLFILE $sbinbuild_dir/mpeuninstall
 #
-    echo "Installed MPE in $DESTDIR$prefix"
+    echo "Installed $pkgname in $DESTDIR$prefix"
     echo "$UNINSTALLFILE may be used to remove the installation"
 fi
 
diff --git a/src/mpe2/src/slog2sdk/sbin/install-package.in b/src/mpe2/src/slog2sdk/sbin/install-package.in
--- a/src/mpe2/src/slog2sdk/sbin/install-package.in
+++ b/src/mpe2/src/slog2sdk/sbin/install-package.in
@@ -14,7 +14,6 @@
 # or different from the source directory
 #
 
-MAKE="@MAKE@"
 PKGS="@subdirs@"
 
 # Source locations
@@ -24,7 +23,6 @@ top_srcdir=@top_srcdir_abs@
 libbuild_dir=@libbuild_dir@
 binbuild_dir=@binbuild_dir@
 docbuild_dir=@docbuild_dir@
-logfilesbuild_dir=@logfilesbuild_dir@
 etcbuild_dir=@etcbuild_dir@
 sharebuild_dir=@sharebuild_dir@
 sbinbuild_dir=@sbinbuild_dir@
@@ -38,20 +36,24 @@ sbindir=@sbindir@
 datadir=@datadir@
 sysconfdir=@sysconfdir@
 docdir=@docdir@
-logfilesdir=@logfilesdir@
 etcdir=$sysconfdir
 sharedir=$datadir
 
 # Determine this package's name
-tmpname="`echo $top_srcdir | sed -e 's%\(.*\)/\([^/]*\)%\2%'`"
-pkgname="`echo $tmpname | sed -e 'y%abcdefghijklmnopqrstuvwxyz/%ABCDEFGHIJKLMNOPQRSTUVWXYZ_%'`"
-if [ "x$pkgname" = "x" ] ; then
-    pkgname="SLOG-2/Jumpshot-4"
+pkgname="`echo $top_srcdir | sed -e 's%\(.*\)/\([^/]*\)%\2%'`"
+titlename="`echo $pkgname | sed -e 'y%abcdefghijklmnopqrstuvwxyz/%ABCDEFGHIJKLMNOPQRSTUVWXYZ_%'`"
+if [ "x$titlename" = "x" ] ; then
+    titlename="SLOG-2/Jumpshot-4"
 fi
+
+MAKE="@MAKE@"
+INSTALL="@INSTALL@"
+RM="@RM@"
 
 # File access mode
 MODE=0644
 XMODE=0755
+DMODE=0755
 replace=1
 # set failmode to soft to let failures accumulate
 failmode="hard"
@@ -103,6 +105,9 @@ for arg in "$@" ; do
         -xmode=*)
             XMODE=`echo $arg | sed -e 's/-xmode=//g'`
             ;;
+        -dmode=*)
+            DMODE=`echo $arg | sed -e 's/-dmode=//g'`
+            ;;
         -copymode=*)
             copymode=`echo $arg | sed -e 's/-copymode=//g'`
             ;;
@@ -116,12 +121,12 @@ for arg in "$@" ; do
         -softchmod)               chmodfailmode="soft" ;;
         -help|-u|-usage|-h)
 cat <<EOF
-Install ${pkgname} into $prefix.
+Install ${titlename} into $prefix.
 -prefix=path     - Destination directory.
 -uninstall=file  - File to append uninstall information to
 -mode=nnnn       - permission mode for regular files.  Default is $MODE .
--xmode=nnnn      - permission mode for execuables and directories.
-                   Default is $XMODE .
+-xmode=nnnn      - permission mode for execuables.  Default is $XMODE .
+-dmode=nnnn      - permission mode for directories.  Default is $DMODE .
 -copymode=xxx    - copy mode for files and directories.  Possible values are
                    {all, core, optional}.
 -noreplace       - Do not replace files found in the installation directory
@@ -149,14 +154,10 @@ fi
 # Start of Routines
 #
 ##############################################################################
-RM="@RM@"
 
-# We could use install, but install is too different and too hard to 
-# test.  So here are the routines to copy file, make directories, and 
-# replace #...# and @...@ in files
-CP=cp
+INSTALLER="$INSTALL"
 #
-CopyFile() {
+InstallFile() {
 if [ -z "$3" ] ; then
     mode=$MODE
 else
@@ -172,73 +173,61 @@ fi
 if [ $replace = 0 -a -f $dest ] ; then
     if [ $verbose = 1 ] ; then echo "$dest exists; not changed" ; fi
 elif [ -d $1 ] ; then
-    echo ">>> $1 is a directory; not copied <<<"
+    echo ">>> $1 is a directory; not installed <<<"
     errs=`expr $errs + 1`
     if [ $failmode = "hard" ] ; then exit 1 ; fi
 elif [ ! -f $1 ] ; then
-    echo "**File $1 does not exist (or is not a regular file)!"
+    echo "*** File $1 does not exist (or is not a regular file)! ***"
     errs=`expr $errs + 1`
     if [ $failmode = "hard" ] ; then exit 1 ; fi
 elif [ "$1" = "$dest" ] ; then
-    echo "**File $1 is being copied to itself!"
+    echo "*** File $1 is being installed to itself! ***"
     errs=`expr $errs + 1`
     if [ $failmode = "hard" ] ; then exit 1 ; fi
 else
-    if [ $verbose = 1 ] ; then echo "Copying $1 to $dest" ; fi
-    # We don't delete the file in the event that we are copying the
+    if [ $verbose = 1 ] ; then echo "Installing $1 to $dest" ; fi
+    # We don't delete the file in the event that we are installing the
     # file over itself (we SHOULD check for that separately, by checking 
     # that directories are distinct)
     if [ -f $dest ] ; then
         echo "Replacing existing file $dest..."
         $Show $RM $dest
     fi
-    $Show $CP $1 $dest
+    if [ "X$mode" != "X" ] ; then
+        $Show $INSTALLER -m $mode $1 $dest
+    else
+        $Show $INSTALLER $1 $dest
+    fi
     rc=$?
     if [ $rc != 0 ] ; then
-        echo "**Error copying file $1 to $dest **"
+        echo "*** Error installing file $1 to $dest with mode $mode. ***"
         errs=`expr $errs + 1`
         if [ $failmode = "hard" ] ; then exit $rc ; fi
     else
-        # store the destination filename copied
+        # store the destination installed filename 
         filelist="$filelist $destfile"
-    fi
-    $Show chmod $mode $dest
-    rc=$?
-    if [ $rc != 0 ] ; then
-        echo "**Error setting mode on file $dest**"
-        errs=`expr $errs + 1`
-        if [ $chmodefailmode = "hard" ] ; then exit $rc ; fi
     fi
 fi
 }
 
 
-#
-# A version of copy file that preserves file dates
-CPRP=cp
-CopyFileP() {
-    CP="$CPRP -p"
-    CopyFile $1 $2 $3
-    CP=cp
-}
-
-
 
 #
-# A version of recursive directory copy that preserves file dates
-# but does NOT copy CVS, old, tex directory. 
+# Recursive directory install that installs or replaces files
+# (file replacement of replace=1) but excluding directories,
+# CVS/, old/ and tex/.
 # $1 is the src directory, $2 is dest directory, $3 is $MODE or $XMODE
-CopyDirRecurP() {
+InstallDirRecur() {
 if [ -n "$1" -a -n "$2" ] ; then
     if [ -d $1 ] ; then
         MkDir $2
         # use $4 as a local variable
         # & set it as the original PWD before "cd $1"
-        set $1 $2 ${3:-$MODE} `pwd`
+        set $1 $2 ${3:-"$MODE"} `pwd`
         cd $1
         for file in * ; do
             if [ -f $file ] ; then
-                CopyFileP $file $2/$file $3
+                InstallFile $file $2/$file $3
             fi
         done
         for dir in * ; do
@@ -246,7 +235,7 @@ if [ -n "$1" -a -n "$2" ] ; then
                  -a "$dir" != "CVS" -a "$dir" != "old" \
                  -a "$dir" != "tex" \
                ] ; then
-                CopyDirRecurP $dir $2/$dir $3
+                InstallDirRecur $dir $2/$dir $3
             fi
         done
         # cd back where it comes from
@@ -273,7 +262,7 @@ if [ ! -d $dest ] ; then
             $Show "mkdir $path_to_date"
             rc=$?
             if [ $rc != 0 ] ; then
-                echo "**Error making directory $dest**"
+                echo "*** Error making directory $dest. ***"
                 errs=`expr $errs + 1`
                 if [ $failmode = "hard" ] ; then exit $rc ; fi
                 echo "Failed to create directory $path_to_date"
@@ -282,12 +271,14 @@ if [ ! -d $dest ] ; then
                 # Note that we store in inverse order
                 dirlist="$1 $dirlist"
             fi
-            $Show chmod $XMODE $path_to_date
-            rc=$?
-            if [ $rc != 0 ] ; then
-                echo "**Error setting mode to $XMODE on directory $path_to_date**"
-                errs=`expr $errs + 1`
-                if [ $chmodfailmode = "hard" ] ; then exit $rc ; fi
+            if [ "X$DMODE" != "X" ] ; then
+                $Show chmod $DMODE $path_to_date
+                rc=$?
+                if [ $rc != 0 ] ; then
+                    echo "*** Error setting mode to $DMODE on directory $path_to_date. ***"
+                    errs=`expr $errs + 1`
+                    if [ $chmodfailmode = "hard" ] ; then exit $rc ; fi
+                fi
             fi
         fi
     done
@@ -316,7 +307,7 @@ fi
 if [ $replace = 0 -a -f $dest ] ; then
     if [ $verbose = 1 ] ; then echo "$dest exists; not changed" ; fi
 elif [ -d $1 ] ; then
-    echo "$1 is a directory; not copied"
+    echo "$1 is a directory; not fixed"
 else
     if [ -f $dest ] ; then $Show $RM $dest ; fi
     if [ $just_testing = 0 ] ; then
@@ -325,15 +316,15 @@ else
         $1 > $dest
         rc=$?
         if [ $rc != 0 ] ; then
-            echo "**Error fixing up file $dest**"
+            echo "*** Error fixing up file $dest. ***"
             errs=`expr $errs + 1`
             if [ $failmode = "hard" ] ; then exit $rc ; fi
         else
-            # store the destination filename copied
+            # store the destination fixed filename
             filelist="$filelist $destfile"
         fi
     else
-        if [ $verbose = 1 ] ; then echo "Fixup $1.in and copy to $dest" ; fi
+        if [ $verbose = 1 ] ; then echo "Fixup $1.in and install to $dest" ; fi
     fi
 fi
 if [ -z "$3" ] ; then
@@ -341,12 +332,14 @@ if [ -z "$3" ] ; then
 else
     mode=$3
 fi
-$Show chmod $mode $dest
-rc=$?
-if [ $rc != 0 ] ; then
-    echo "**Error setting mode on file $dest**"
-    errs=`expr $errs + 1`
-    if [ $failmode = "hard" ] ; then exit $rc ; fi
+if [ "X$mode" != "X" ] ; then
+    $Show chmod $mode $dest
+    rc=$?
+    if [ $rc != 0 ] ; then
+        echo "*** Error setting mode on file $dest. ***"
+        errs=`expr $errs + 1`
+        if [ $failmode = "hard" ] ; then exit $rc ; fi
+    fi
 fi
 }
 
@@ -380,7 +373,6 @@ if [ "$prefix_override" = 1 ] ; then
     docdir=$prefix/doc
     etcdir=$prefix/etc
     sharedir=$prefix/share
-    logfilesdir=$prefix/logfiles
     if [ $appendUninstall = 0 ] ; then
         UNINSTALLFILE=$DESTDIR${sbindir}/${UNINSTALL_base}
     fi
@@ -398,51 +390,31 @@ fi
 uninstall_dirname=`dirname $UNINSTALLFILE`
 if [ "$uninstall_dirname" = "$DESTDIR$sbindir" ] ; then
     if [ ! -d $DESTDIR$sbindir ] ; then
-        echo "Creating ${pkgname}'s sbin"
+        echo "Creating ${titlename}'s sbin"
         MkDir $sbindir
     fi
 fi
 
 if [ "$copymode" = "all" -o "$copymode" = "core" ] ; then
-    for type in lib doc logfiles etc ; do
-        fromdir_name=${type}build_dir
-        todir_name=${type}dir
-        eval fromdir_value=\$"$fromdir_name"
-        eval todir_value=\$"$todir_name"
-        if [ -n "$fromdir_value" ] ; then
-            if [ -d $fromdir_value ] ; then
-                echo "Copying ${pkgname}'s $type"
-                if [ $verbose = 1 ] ; then
-                    echo "$fromdir_value -> $DESTDIR$todir_value"
-                fi
-                CopyDirRecurP $fromdir_value $todir_value $MODE
-            fi
-        fi 
-    done
-fi
-
-if [ "$copymode" = "all" ] ; then
-    if [ -n "$PKGS" ] ; then
-        if [ ! -d $DESTDIR$sharedir ] ; then
-            echo "Creating ${pkgname}'s share"
-            MkDir $sharedir
-        fi
+    if [ ! -d $DESTDIR$sharedir ] ; then
+        echo "Creating ${titlename}'s share"
+        MkDir $sharedir
     fi
 
-    for type in share ; do
+    for type in lib doc share etc ; do
         fromdir_name=${type}build_dir
         todir_name=${type}dir
         eval fromdir_value=\$"$fromdir_name"
         eval todir_value=\$"$todir_name"
         if [ -n "$fromdir_value" ] ; then
             if [ -d $fromdir_value ] ; then
-                echo "Copying ${pkgname}'s $type"
+                echo "Installing ${titlename}'s $type"
                 if [ $verbose = 1 ] ; then
                     echo "$fromdir_value -> $DESTDIR$todir_value"
                 fi
-                CopyDirRecurP $fromdir_value $todir_value $MODE
+                InstallDirRecur $fromdir_value $todir_value $MODE
             fi
-        fi
+        fi 
     done
 fi
 
@@ -450,7 +422,7 @@ if [ "$copymode" = "all" -o "$copymode" = "core" ] ; then
     EXEFILES="@EXEFILES@"
     if [ -n "$binbuild_dir" ] ; then
         if [ -d $binbuild_dir ] ; then
-            echo "Creating ${pkgname}'s bin"
+            echo "Creating ${titlename}'s bin"
             MkDir $bindir
             for exefile in $EXEFILES ; do
                 if [ -x $binbuild_dir/$exefile ] ; then
@@ -463,11 +435,11 @@ if [ "$copymode" = "all" -o "$copymode" = "core" ] ; then
 fi
     
 if [ "$copymode" = "all" -o "$copymode" = "optional" ] ; then
-    CopyFileP $top_srcdir/COPYRIGHT           $prefix
-    CopyFileP $top_srcdir/CHANGES             $prefix
-    CopyFileP $top_srcdir/FAQ                 $prefix
-    CopyFileP $top_srcdir/README.sdk          $prefix
-    CopyFileP $top_srcdir/README.rte          $prefix
+    InstallFile $top_srcdir/COPYRIGHT           $prefix
+    InstallFile $top_srcdir/CHANGES             $prefix
+    InstallFile $top_srcdir/FAQ                 $prefix
+    InstallFile $top_srcdir/README.sdk          $prefix
+    InstallFile $top_srcdir/README.rte          $prefix
 fi
 
 # Remove old uninstall file & Prepare the UNINSTALLFILE for appending
@@ -487,41 +459,22 @@ if [ "$UNINSTALLFILE" != "/dev/null" ] ; then
     chmod u+x $UNINSTALLFILE
 fi
 
-# Install subpackages as specified in $PKGS
-if [ "$copymode" = "core" ] ; then
-    for pkg in $PKGS ; do
-        if [ -d $binbuild_dir/../$pkg ] ; then
-            if [ "X$pkg" = "Xtrace_rlog" ] ; then
-                ( cd $binbuild_dir/../$pkg && \
-                  if [ -x ./sbin/install-package ] ; then \
-                      ./sbin/install-package -prefix=$prefix \
-                                             -uninstall=$UNINSTALLFILE \
-                                             -mode=$MODE -xmode=$XMODE ; \
-                  fi )
-            fi
-        fi
-    done
+base_install_opts="-mode=$MODE -xmode=$XMODE -dmode=$DMODE"
+base_install_opts="-uninstall=$UNINSTALLFILE $base_install_opts"
+if [ "$prefix_override" = 1 ] ; then
+    install_opts="-prefix=$prefix $base_install_opts"
+else
+    install_opts="$base_install_opts"
 fi
 
-if [ "$copymode" = "all" ] ; then
+# Install subpackages as specified in $PKGS
+if [ "$copymode" = "all" -o "$copymode" = "core" ] ; then
     for pkg in $PKGS ; do
         if [ -d $binbuild_dir/../$pkg ] ; then
-            if [ "X$pkg" = "Xtrace_rlog" ] ; then
-                ( cd $binbuild_dir/../$pkg && \
-                  if [ -x ./sbin/install-package ] ; then \
-                      ./sbin/install-package -prefix=$prefix \
-                                             -uninstall=$UNINSTALLFILE \
-                                             -mode=$MODE -xmode=$XMODE ; \
-                  fi )
-            else
-                ( cd $binbuild_dir/../$pkg && \
-                  if [    -x ./sbin/install-package \
-                       -a -d $DESTDIR$sharedir ] ; then \
-                      ./sbin/install-package -prefix=$sharedir/$pkg \
-                                             -uninstall=$UNINSTALLFILE \
-                                             -mode=$MODE -xmode=$XMODE ; \
-                  fi )
-            fi
+            ( cd $binbuild_dir/../$pkg && \
+              if [ -x ./sbin/install-package ] ; then \
+                  ./sbin/install-package $install_opts ; \
+              fi )
         fi
     done
 fi
@@ -538,7 +491,7 @@ for dir in $dirlist ; do
 done
 
 #
-echo "Installed ${pkgname} in $DESTDIR$prefix"
+echo "Installed ${titlename} in $DESTDIR$prefix"
 echo "$UNINSTALLFILE may be used to remove the installation"
 #
 if [ $errs -gt 0 ] ; then
diff --git a/src/mpe2/src/slog2sdk/trace_sample/sbin/install-package.in b/src/mpe2/src/slog2sdk/trace_sample/sbin/install-package.in
--- a/src/mpe2/src/slog2sdk/trace_sample/sbin/install-package.in
+++ b/src/mpe2/src/slog2sdk/trace_sample/sbin/install-package.in
@@ -14,8 +14,6 @@
 # or different from the source directory
 #
 
-MAKE="@MAKE@"
-
 # Source locations
 top_srcdir=@top_srcdir_abs@
 
@@ -23,7 +21,7 @@ top_srcdir=@top_srcdir_abs@
 libbuild_dir=@libbuild_dir@
 binbuild_dir=@binbuild_dir@
 sbinbuild_dir=@sbinbuild_dir@
-logfilesbuild_dir=@logfilesbuild_dir@
+sharebuild_dir=@sharebuild_dir@
 
 # Installation directories: Default paths (set at configure time)
 prefix=@prefix@
@@ -33,21 +31,25 @@ bindir=@bindir@
 sbindir=@sbindir@
 datadir=@datadir@
 sysconfdir=@sysconfdir@
-logfilesdir=$prefix/logfiles
 etcdir=$sysconfdir
 sharedir=$datadir
 gui_libdir="`echo $prefix | sed -e 's%\(.*\)/[^/]*/[^/]*$%\1/lib%'`"
 
 # Determine this package's name
-tmpname="`echo $top_srcdir | sed -e 's%\(.*\)/\([^/]*\)%\2%'`"
-pkgname="`echo $tmpname | sed -e 'y%abcdefghijklmnopqrstuvwxyz/%ABCDEFGHIJKLMNOPQRSTUVWXYZ_%'`"
-if [ "x$pkgname" = "x" ] ; then
-    pkgname="TRACE-IMPL"
+pkgname="`echo $top_srcdir | sed -e 's%\(.*\)/\([^/]*\)%\2%'`"
+titlename="`echo $pkgname | sed -e 'y%abcdefghijklmnopqrstuvwxyz/%ABCDEFGHIJKLMNOPQRSTUVWXYZ_%'`"
+if [ "x$titlename" = "x" ] ; then
+    titlename="TRACE-IMPL"
 fi
+
+MAKE="@MAKE@"
+INSTALL="@INSTALL@"
+RM="@RM@"
 
 # File access mode
 MODE=0644
 XMODE=0755
+DMODE=0755
 replace=1
 # set failmode to soft to let failures accumulate
 failmode="hard"
@@ -97,6 +99,9 @@ for arg in "$@" ; do
         -xmode=*)
             XMODE=`echo $arg | sed -e 's/-xmode=//g'`
             ;;
+        -dmode=*)
+            DMODE=`echo $arg | sed -e 's/-dmode=//g'`
+            ;;
         -echo)                    set -x ;;
         -noreplace|-no_replace)   replace=0 ;;
         -replace)                 replace=1 ;;
@@ -107,11 +112,12 @@ for arg in "$@" ; do
         -softchmod)               chmodfailmode="soft" ;;
         -help|-u|-usage|-h)
 cat <<EOF
-Install $pkgname into $prefix.
+Install $titlename into $prefix.
 -prefix=path     - Destination directory.
 -uninstall=file  - File to append uninstall information to
 -mode=nnnn       - mode for regular files.  Default is $MODE .
--xmode=nnnn      - mode for execuables and directories.  Default is $XMODE .
+-xmode=nnnn      - mode for execuables.  Default is $XMODE .
+-dmode=nnnn      - mode for directories.  Default is $DMODE .
 -noreplace       - Do not replace files found in the installation directory
 -soft		 - Do not abort on failure
 -softchmod       - Do not abort on failure of chmod
@@ -137,14 +143,10 @@ fi
 # Start of Routines
 #
 ##############################################################################
-RM="@RM@"
 
-# We could use install, but install is too different and too hard to 
-# test.  So here are the routines to copy file, make directories, and 
-# replace #...# and @...@ in files
-CP=cp
+INSTALLER="$INSTALL"
 #
-CopyFile() {
+InstallFile() {
 if [ -z "$3" ] ; then
     mode=$MODE
 else
@@ -160,73 +162,61 @@ fi
 if [ $replace = 0 -a -f $dest ] ; then
     if [ $verbose = 1 ] ; then echo "$dest exists; not changed" ; fi
 elif [ -d $1 ] ; then
-    echo ">>> $1 is a directory; not copied <<<"
+    echo ">>> $1 is a directory; not installed <<<"
     errs=`expr $errs + 1`
     if [ $failmode = "hard" ] ; then exit 1 ; fi
 elif [ ! -f $1 ] ; then
-    echo "**File $1 does not exist (or is not a regular file)!"
+    echo "*** File $1 does not exist (or is not a regular file)! ***"
     errs=`expr $errs + 1`
     if [ $failmode = "hard" ] ; then exit 1 ; fi
 elif [ "$1" = "$dest" ] ; then
-    echo "**File $1 is being copied to itself!"
+    echo "*** File $1 is being installed to itself! ***"
     errs=`expr $errs + 1`
     if [ $failmode = "hard" ] ; then exit 1 ; fi
 else
-    if [ $verbose = 1 ] ; then echo "Copying $1 to $dest" ; fi
-    # We don't delete the file in the event that we are copying the
+    if [ $verbose = 1 ] ; then echo "Installing $1 to $dest" ; fi
+    # We don't delete the file in the event that we are installing the
     # file over itself (we SHOULD check for that separately, by checking 
     # that directories are distinct)
     if [ -f $dest ] ; then
         echo "Replacing existing file $dest..."
         $Show $RM $dest
     fi
-    $Show $CP $1 $dest
+    if [ "X$mode" != "X" ] ; then
+        $Show $INSTALLER -m $mode $1 $dest
+    else
+        $Show $INSTALLER $1 $dest
+    fi
     rc=$?
     if [ $rc != 0 ] ; then
-        echo "**Error copying file $1 to $dest **"
+        echo "*** Error installing file $1 to $dest with mode $mode. ***"
         errs=`expr $errs + 1`
         if [ $failmode = "hard" ] ; then exit $rc ; fi
     else
-        # store the destination filename copied
+        # store the destination installed filename
         filelist="$filelist $destfile"
-    fi
-    $Show chmod $mode $dest
-    rc=$?
-    if [ $rc != 0 ] ; then
-        echo "**Error setting mode on file $dest**"
-        errs=`expr $errs + 1`
-        if [ $chmodefailmode = "hard" ] ; then exit $rc ; fi
     fi
 fi
 }
 
 
-#
-# A version of copy file that preserves file dates
-CPRP=cp
-CopyFileP() {
-    CP="$CPRP -p"
-    CopyFile $1 $2 $3
-    CP=cp
-}
-
-
 
 #
-# A version of recursive directory copy that preserves file dates
-# but does NOT copy CVS, old, tex directory. 
+# Recursive directory install that installs or replaces files
+# (file replacement of replace=1) but excluding directories,
+# CVS/, old/ and tex/.
 # $1 is the src directory, $2 is dest directory, $3 is $MODE or $XMODE
-CopyDirRecurP() {
+InstallDirRecur() {
 if [ -n "$1" -a -n "$2" ] ; then
     if [ -d $1 ] ; then
         MkDir $2
         # use $4 as a local variable
         # & set it as the original PWD before "cd $1"
-        set $1 $2 ${3:-$MODE} `pwd`
+        set $1 $2 ${3:-"$MODE"} `pwd`
         cd $1
         for file in * ; do
             if [ -f $file ] ; then
-                CopyFileP $file $2/$file $3
+                InstallFile $file $2/$file $3
             fi
         done
         for dir in * ; do
@@ -234,7 +224,7 @@ if [ -n "$1" -a -n "$2" ] ; then
                  -a "$dir" != "CVS" -a "$dir" != "old" \
                  -a "$dir" != "tex" \
                ] ; then
-                CopyDirRecurP $dir $2/$dir $3
+                InstallDirRecur $dir $2/$dir $3
             fi
         done
         # cd back where it comes from
@@ -261,7 +251,7 @@ if [ ! -d $dest ] ; then
             $Show "mkdir $path_to_date"
             rc=$?
             if [ $rc != 0 ] ; then
-                echo "**Error making directory $dest**"
+                echo "*** Error making directory $dest. ***"
                 errs=`expr $errs + 1`
                 if [ $failmode = "hard" ] ; then exit $rc ; fi
                 echo "Failed to create directory $path_to_date"
@@ -270,12 +260,14 @@ if [ ! -d $dest ] ; then
                 # Note that we store in inverse order
                 dirlist="$1 $dirlist"
             fi
-            $Show chmod $XMODE $path_to_date
-            rc=$?
-            if [ $rc != 0 ] ; then
-                echo "**Error setting mode to $XMODE on directory $path_to_date**"
-                errs=`expr $errs + 1`
-                if [ $chmodfailmode = "hard" ] ; then exit $rc ; fi
+            if [ "X$DMODE" != "X" ] ; then
+                $Show chmod $DMODE $path_to_date
+                rc=$?
+                if [ $rc != 0 ] ; then
+                    echo "*** Error setting mode to $DMODE on directory $path_to_date. ***"
+                    errs=`expr $errs + 1`
+                    if [ $chmodfailmode = "hard" ] ; then exit $rc ; fi
+                fi
             fi
         fi
     done
@@ -294,7 +286,6 @@ FixupFileForInstall() {
     # Change the FIRST libpath to the new form.  This allows 
     # the LIB_PATH to contain multiple names, as long as the MPICH libpath
     # is first
-dest=$DESTDIR$2
 if [ -d $DESTDIR$2 ] ; then
     dest=$DESTDIR$2/`basename $1`
     destfile=$2/`basename $1`
@@ -305,25 +296,25 @@ fi
 if [ $replace = 0 -a -f $dest ] ; then
     if [ $verbose = 1 ] ; then echo "$dest exists; not changed" ; fi
 elif [ -d $1 ] ; then
-    echo "$1 is a directory; not copied"
+    echo "$1 is a directory; not fixed"
 else
     if [ -f $dest ] ; then $Show $RM $dest ; fi
     if [ $just_testing = 0 ] ; then
         sed \
-        -e "s%^TRACE_LIBDIR=.*%TRACE_LIBDIR=$libdir%g" \
-        -e "s%^GUI_LIBDIR=.*%GUI_LIBDIR=$gui_libdir%g" \
+        -e "s%^TRACE_LIBDIR=.*%TRACE_LIBDIR=$libdir/$pkgname%g" \
+        -e "s%^GUI_LIBDIR=.*%GUI_LIBDIR=$libdir%g" \
         $1 > $dest
         rc=$?
         if [ $rc != 0 ] ; then
-            echo "**Error fixing up file $dest**"
+            echo "*** Error fixing up file $dest. ***"
             errs=`expr $errs + 1`
             if [ $failmode = "hard" ] ; then exit $rc ; fi
         else
-            # store the destination filename copied
+            # store the destination installed filename
             filelist="$filelist $destfile"
         fi
     else
-        if [ $verbose = 1 ] ; then echo "Fixup $1.in and copy to $dest" ; fi
+        if [ $verbose = 1 ] ; then echo "Fixup $1.in and install to $dest" ; fi
     fi
 fi
 if [ -z "$3" ] ; then
@@ -331,12 +322,14 @@ if [ -z "$3" ] ; then
 else
     mode=$3
 fi
-$Show chmod $mode $dest
-rc=$?
-if [ $rc != 0 ] ; then
-    echo "**Error setting mode on file $dest**"
-    errs=`expr $errs + 1`
-    if [ $failmode = "hard" ] ; then exit $rc ; fi
+if [ "X$mode" != "X" ] ; then
+    $Show chmod $mode $dest
+    rc=$?
+    if [ $rc != 0 ] ; then
+        echo "*** Error setting mode on file $dest. ***"
+        errs=`expr $errs + 1`
+        if [ $failmode = "hard" ] ; then exit $rc ; fi
+    fi
 fi
 }
 
@@ -367,7 +360,7 @@ if [ "$prefix_override" = 1 ] ; then
     libdir=$prefix/lib
     bindir=$prefix/bin
     sbindir=$prefix/sbin
-    logfilesdir=$prefix/logfiles
+    sharedir=$prefix/share
     gui_libdir="`echo $prefix | sed -e 's%\(.*\)/[^/]*/[^/]*$%\1/lib%'`"
     if [ $appendUninstall = 0 ] ; then
         UNINSTALLFILE=$DESTDIR${sbindir}/${UNINSTALL_base}
@@ -380,41 +373,51 @@ fi
 uninstall_dirname=`dirname $UNINSTALLFILE`
 if [ "$uninstall_dirname" = "$DESTDIR$sbindir" ] ; then
     if [ ! -d $DESTDIR$sbindir ] ; then
-        echo "Creating ${pkgname}'s sbin"
+        echo "Creating ${titlename}'s sbin"
         MkDir $sbindir
     fi
 fi
 
-# Copy libraries
-for type in lib logfiles ; do
+if [ ! -d $DESTDIR$sharedir ] ; then
+    echo "Creating ${titlename}'s share"
+    MkDir $sharedir
+fi
+
+for type in share ; do
     fromdir_name=${type}build_dir
     todir_name=${type}dir
     eval fromdir_value=\$"$fromdir_name"
     eval todir_value=\$"$todir_name"
     if [ -n "$fromdir_value" ] ; then
         if [ -d $fromdir_value ] ; then
-            echo "Copying ${pkgname}'s $type"
+            echo "Installing ${titlename}'s $type"
             if [ $verbose = 1 ] ; then
                 echo "$fromdir_value -> $DESTDIR$todir_value"
             fi
-            CopyDirRecurP $fromdir_value $todir_value $MODE
+            InstallDirRecur $fromdir_value $todir_value $MODE
         fi
     fi
 done
 
-cd $libbuild_dir/../src && $MAKE INSTALL_LIBSO LIBDIR=$libdir
+# Install libraries
+if [ ! -d $DESTDIR$libdir/$pkgname ] ; then
+    echo "Creating ${titlename}'s lib"
+    MkDir $libdir/$pkgname
+fi
+
+cd $libbuild_dir/../src && $MAKE INSTALL_LIBSO LIBDIR=$libdir/$pkgname
 
 EXEFILES="@EXEFILES@"
 
-# Copy utility programs
+# Install utility programs
 if [ -n "$binbuild_dir" ] ; then
     if [ -d $binbuild_dir ] ; then
-        echo "Copying ${pkgname}'s bin"
+        echo "Installing ${titlename}'s bin"
         if [ $verbose = 1 ] ; then
             echo "$binbuild_dir -> $DESTDIR$bindir"
         fi
-#       Copying all
-        CopyDirRecurP $binbuild_dir $bindir $XMODE
+#       Installing all
+        InstallDirRecur $binbuild_dir $bindir $XMODE
 #       Fixing up the scripts
         for exefile in $EXEFILES ; do
             if [ -x $binbuild_dir/$exefile ] ; then
@@ -455,7 +458,7 @@ for dir in $dirlist ; do
 done
 
 #
-echo "Installed ${pkgname} in $prefix"
+echo "Installed ${titlename} in $prefix"
 echo "$UNINSTALLFILE may be used to remove the installation"
 #
 if [ $errs -gt 0 ] ; then
diff --git a/src/mpid/ch3/channels/shm/configure b/src/mpid/ch3/channels/shm/configure
--- a/src/mpid/ch3/channels/shm/configure
+++ b/src/mpid/ch3/channels/shm/configure
@@ -272,7 +272,7 @@ PACKAGE_STRING=
 PACKAGE_BUGREPORT=
 
 ac_unique_file="configure.in"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAKE VPATH SET_CFLAGS SET_MAKE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP device_name channel_name SHM_LIBS AR RANLIB MPILIBNAME CC_SHL C_LINK_SHL LIBTOOL ENABLE_SHLIB master_top_srcdir master_top_builddir MAKE_DEPEND_C LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAKE VPATH SET_CFLAGS SET_MAKE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP device_name channel_name SHM_LIBS AR RANLIB MPILIBNAME CC_SHL C_LINK_SHL LIBTOOL ENABLE_SHLIB master_top_srcdir master_top_builddir MAKE_DEPEND_C ETAGS ETAGSADD LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1380,15 +1380,69 @@ ac_configure=$ac_aux_dir/configure # This should be Cygnus configure.
           ac_config_headers="$ac_config_headers include/mpidi_ch3i_shm_conf.h"
 
 
+
+
+
+
 echo "RUNNING CONFIGURE FOR THE SHARED MEMORY CHANNEL"
 
-if test "`cd $srcdir && pwd`" != "`pwd`" && test -f $srcdir/config.status ; then
-    { { echo "$as_me:$LINENO: error: You cannot do a VPATH build if the source directory has been
-    configured.  Run \"make distclean\" in $srcdir first." >&5
+
+rm -f conftest*
+date >conftest$$
+# If creating a file in the current directory does not show up in the srcdir
+# then we're doing a VPATH build (or something is very wrong)
+if test ! -s $srcdir/conftest$$ ; then
+    pac_dirtyfiles=""
+    pac_dirtydirs=""
+    pac_header=""
+
+    for file in config.status $pac_header  ; do
+        if test -f $srcdir/$file ; then
+	    pac_dirtyfiles="$pac_dirtyfiles $file"
+	fi
+    done
+
+
+    if test -n "$pac_dirtyfiles" -o -n "$pac_dirtydirs" ; then
+	# Create a nice message about what to remove
+	rmmsg=""
+	if test -n "$pac_dirtyfiles" ; then
+	    rmmsg="files $pac_dirtyfiles"
+        fi
+ 	if test -n "$pac_dirtydirs" ; then
+	    if test -n "$rmmsg" ; then
+	        rmmsg="$rmmsg and directories $pac_dirtydirs"
+            else
+                rmmsg="directories $pac_dirtydirs"
+            fi
+        fi
+        if test -f $srcdir/Makefile ; then
+            { { echo "$as_me:$LINENO: error: You cannot do a VPATH build if the source directory has been
+    configured.  Run \"make distclean\" in $srcdir first and make sure that the
+    $rmmsg have been removed." >&5
 echo "$as_me: error: You cannot do a VPATH build if the source directory has been
-    configured.  Run \"make distclean\" in $srcdir first." >&2;}
+    configured.  Run \"make distclean\" in $srcdir first and make sure that the
+    $rmmsg have been removed." >&2;}
    { (exit 1); exit 1; }; }
+        else
+            { { echo "$as_me:$LINENO: error: You cannot do a VPATH build if the source directory has been
+    configured.  Remove the $rmmsg in $srcdir." >&5
+echo "$as_me: error: You cannot do a VPATH build if the source directory has been
+    configured.  Remove the $rmmsg in $srcdir." >&2;}
+   { (exit 1); exit 1; }; }
+        fi
+    fi
 fi
+rm -f conftest*
+
+
+
+if test -n "$CONF_BASE_CACHEFILE" -a -s "$CONF_BASE_CACHEFILE" ; then
+    echo "Loading base cachefile $CONF_BASE_CACHEFILE"
+    . $CONF_BASE_CACHEFILE
+    export CONF_BASE_CACHEFILE
+fi
+
 
 
 true
@@ -2614,7 +2668,8 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
-for ac_func in sysconf shmget shmat shmdt shmctl mmap
+
+for ac_func in sysconf sysctl shmget shmat shmdt shmctl mmap
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
 echo "$as_me:$LINENO: checking for $ac_func" >&5
@@ -3304,6 +3359,7 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
+
 for ac_header in \
     assert.h					\
     errno.h					\
@@ -3317,6 +3373,7 @@ for ac_header in \
     sys/socket.h netinet/in.h \
     fcntl.h sys/mman.h \
     sys/ptrace.h \
+    sys/sysctl.h \
 
 do
 ac_safe=`echo "$ac_header" | sed 'y%./+-%__p_%'`
@@ -3366,7 +3423,7 @@ fi
 # If cpp failed, see if the compiler accepts the header.
 if test "$pac_found_header" != "yes" ; then
     cat >conftest.c<<EOF
-#line 3369 "configure"
+#line 3426 "configure"
 #include "confdefs.h"
 #include <$ac_header>
 int conftest() {return 0;}
@@ -3591,6 +3648,23 @@ echo "$as_me: WARNING: libtool selected for shared library support but LIBTOOL i
 
 
 
+
+
+
+
+export ETAGS
+export ETAGSADD
+
+
+if test -n "$CONF_BASE_CACHEFILE" -a -s "$CONF_BASE_CACHEFILE" ; then
+    set | grep ac_cv > $CONF_BASE_CACHEFILE.new
+    if cmp -s $CONF_BASE_CACHEFILE.new $CONF_BASE_CACHEFILE ; then
+	:
+    else
+	echo "Replacing $CONF_BASE_CACHEFILE"
+	mv $CONF_BASE_CACHEFILE.new $CONF_BASE_CACHEFILE
+    fi
+fi
 
 
                               ac_config_files="$ac_config_files Makefile src/Makefile localdefs"
@@ -4231,6 +4305,8 @@ s,@ENABLE_SHLIB@,$ENABLE_SHLIB,;t t
 s,@master_top_srcdir@,$master_top_srcdir,;t t
 s,@master_top_builddir@,$master_top_builddir,;t t
 s,@MAKE_DEPEND_C@,$MAKE_DEPEND_C,;t t
+s,@ETAGS@,$ETAGS,;t t
+s,@ETAGSADD@,$ETAGSADD,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
diff --git a/src/mpid/ch3/channels/sock/configure b/src/mpid/ch3/channels/sock/configure
--- a/src/mpid/ch3/channels/sock/configure
+++ b/src/mpid/ch3/channels/sock/configure
@@ -1380,15 +1380,69 @@ ac_configure=$ac_aux_dir/configure # This should be Cygnus configure.
           ac_config_headers="$ac_config_headers include/mpidi_ch3i_sock_conf.h"
 
 
+
+
+
+
 echo "RUNNING CONFIGURE FOR THE SOCK CHANNEL"
 
-if test "`cd $srcdir && pwd`" != "`pwd`" && test -f $srcdir/config.status ; then
-    { { echo "$as_me:$LINENO: error: You cannot do a VPATH build if the source directory has been
-    configured.  Run \"make distclean\" in $srcdir first." >&5
+
+rm -f conftest*
+date >conftest$$
+# If creating a file in the current directory does not show up in the srcdir
+# then we're doing a VPATH build (or something is very wrong)
+if test ! -s $srcdir/conftest$$ ; then
+    pac_dirtyfiles=""
+    pac_dirtydirs=""
+    pac_header=""
+
+    for file in config.status $pac_header  ; do
+        if test -f $srcdir/$file ; then
+	    pac_dirtyfiles="$pac_dirtyfiles $file"
+	fi
+    done
+
+
+    if test -n "$pac_dirtyfiles" -o -n "$pac_dirtydirs" ; then
+	# Create a nice message about what to remove
+	rmmsg=""
+	if test -n "$pac_dirtyfiles" ; then
+	    rmmsg="files $pac_dirtyfiles"
+        fi
+ 	if test -n "$pac_dirtydirs" ; then
+	    if test -n "$rmmsg" ; then
+	        rmmsg="$rmmsg and directories $pac_dirtydirs"
+            else
+                rmmsg="directories $pac_dirtydirs"
+            fi
+        fi
+        if test -f $srcdir/Makefile ; then
+            { { echo "$as_me:$LINENO: error: You cannot do a VPATH build if the source directory has been
+    configured.  Run \"make distclean\" in $srcdir first and make sure that the
+    $rmmsg have been removed." >&5
 echo "$as_me: error: You cannot do a VPATH build if the source directory has been
-    configured.  Run \"make distclean\" in $srcdir first." >&2;}
+    configured.  Run \"make distclean\" in $srcdir first and make sure that the
+    $rmmsg have been removed." >&2;}
    { (exit 1); exit 1; }; }
+        else
+            { { echo "$as_me:$LINENO: error: You cannot do a VPATH build if the source directory has been
+    configured.  Remove the $rmmsg in $srcdir." >&5
+echo "$as_me: error: You cannot do a VPATH build if the source directory has been
+    configured.  Remove the $rmmsg in $srcdir." >&2;}
+   { (exit 1); exit 1; }; }
+        fi
+    fi
 fi
+rm -f conftest*
+
+
+
+if test -n "$CONF_BASE_CACHEFILE" -a -s "$CONF_BASE_CACHEFILE" ; then
+    echo "Loading base cachefile $CONF_BASE_CACHEFILE"
+    . $CONF_BASE_CACHEFILE
+    export CONF_BASE_CACHEFILE
+fi
+
 
 
 true
@@ -2931,7 +2985,7 @@ fi
 # If cpp failed, see if the compiler accepts the header.
 if test "$pac_found_header" != "yes" ; then
     cat >conftest.c<<EOF
-#line 2934 "configure"
+#line 2988 "configure"
 #include "confdefs.h"
 #include <$ac_header>
 int conftest() {return 0;}
@@ -3040,6 +3094,9 @@ _ACEOF
 
 fi
 
+# We need the util/sock/ch3usock.h header file
+CPPFLAGS="${CPPFLAGS} -I${master_top_srcdir}/src/mpid/ch3/util/sock"
+
 
 
 
@@ -3075,6 +3132,18 @@ fi
 
 export ETAGS
 export ETAGSADD
+
+
+if test -n "$CONF_BASE_CACHEFILE" -a -s "$CONF_BASE_CACHEFILE" ; then
+    set | grep ac_cv > $CONF_BASE_CACHEFILE.new
+    if cmp -s $CONF_BASE_CACHEFILE.new $CONF_BASE_CACHEFILE ; then
+	:
+    else
+	echo "Replacing $CONF_BASE_CACHEFILE"
+	mv $CONF_BASE_CACHEFILE.new $CONF_BASE_CACHEFILE
+    fi
+fi
+
 
                               ac_config_files="$ac_config_files Makefile src/Makefile localdefs"
 cat >confcache <<\_ACEOF
diff --git a/src/mpid/ch3/channels/ssm/configure b/src/mpid/ch3/channels/ssm/configure
--- a/src/mpid/ch3/channels/ssm/configure
+++ b/src/mpid/ch3/channels/ssm/configure
@@ -309,7 +309,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAKE VPATH SET_CFLAGS SET_MAKE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP EGREP device_name channel_name SSM_LIBS AR RANLIB MPILIBNAME CC_SHL C_LINK_SHL LIBTOOL ENABLE_SHLIB master_top_srcdir master_top_builddir MAKE_DEPEND_C LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAKE VPATH SET_CFLAGS SET_MAKE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP EGREP device_name channel_name SSM_LIBS AR RANLIB MPILIBNAME CC_SHL C_LINK_SHL LIBTOOL ENABLE_SHLIB master_top_srcdir master_top_builddir MAKE_DEPEND_C ETAGS ETAGSADD LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1422,18 +1422,72 @@ ac_configure=$ac_aux_dir/configure # This should be Cygnus configure.
           ac_config_headers="$ac_config_headers include/mpidi_ch3i_ssm_conf.h"
 
 
+
+
+
+
 echo "RUNNING CONFIGURE FOR THE SOCK-SHARED_MEMORY CHANNEL"
 
 save_libs=$LIBS
 LIBS=
 
-if test "`cd $srcdir && pwd`" != "`pwd`" && test -f $srcdir/config.status ; then
-    { { echo "$as_me:$LINENO: error: You cannot do a VPATH build if the source directory has been
-    configured.  Run \"make distclean\" in $srcdir first." >&5
+
+rm -f conftest*
+date >conftest$$
+# If creating a file in the current directory does not show up in the srcdir
+# then we're doing a VPATH build (or something is very wrong)
+if test ! -s $srcdir/conftest$$ ; then
+    pac_dirtyfiles=""
+    pac_dirtydirs=""
+    pac_header=""
+
+    for file in config.status $pac_header  ; do
+        if test -f $srcdir/$file ; then
+	    pac_dirtyfiles="$pac_dirtyfiles $file"
+	fi
+    done
+
+
+    if test -n "$pac_dirtyfiles" -o -n "$pac_dirtydirs" ; then
+	# Create a nice message about what to remove
+	rmmsg=""
+	if test -n "$pac_dirtyfiles" ; then
+	    rmmsg="files $pac_dirtyfiles"
+        fi
+ 	if test -n "$pac_dirtydirs" ; then
+	    if test -n "$rmmsg" ; then
+	        rmmsg="$rmmsg and directories $pac_dirtydirs"
+            else
+                rmmsg="directories $pac_dirtydirs"
+            fi
+        fi
+        if test -f $srcdir/Makefile ; then
+            { { echo "$as_me:$LINENO: error: You cannot do a VPATH build if the source directory has been
+    configured.  Run \"make distclean\" in $srcdir first and make sure that the
+    $rmmsg have been removed." >&5
 echo "$as_me: error: You cannot do a VPATH build if the source directory has been
-    configured.  Run \"make distclean\" in $srcdir first." >&2;}
+    configured.  Run \"make distclean\" in $srcdir first and make sure that the
+    $rmmsg have been removed." >&2;}
    { (exit 1); exit 1; }; }
+        else
+            { { echo "$as_me:$LINENO: error: You cannot do a VPATH build if the source directory has been
+    configured.  Remove the $rmmsg in $srcdir." >&5
+echo "$as_me: error: You cannot do a VPATH build if the source directory has been
+    configured.  Remove the $rmmsg in $srcdir." >&2;}
+   { (exit 1); exit 1; }; }
+        fi
+    fi
 fi
+rm -f conftest*
+
+
+
+if test -n "$CONF_BASE_CACHEFILE" -a -s "$CONF_BASE_CACHEFILE" ; then
+    echo "Loading base cachefile $CONF_BASE_CACHEFILE"
+    . $CONF_BASE_CACHEFILE
+    export CONF_BASE_CACHEFILE
+fi
+
 
 
 true
@@ -2926,7 +2980,7 @@ fi
 # If cpp failed, see if the compiler accepts the header.
 if test "$pac_found_header" != "yes" ; then
     cat >conftest.c<<EOF
-#line 2929 "configure"
+#line 2983 "configure"
 #include "confdefs.h"
 #include <$ac_header>
 int conftest() {return 0;}
@@ -3273,7 +3327,7 @@ fi
 # If cpp failed, see if the compiler accepts the header.
 if test "$pac_found_header" != "yes" ; then
     cat >conftest.c<<EOF
-#line 3276 "configure"
+#line 3330 "configure"
 #include "confdefs.h"
 #include <$ac_header>
 int conftest() {return 0;}
@@ -3321,7 +3375,8 @@ done
 
 
 
-for ac_header in sys/stat.h sys/ptrace.h sys/wait.h errno.h ctype.h process.h sys/mman.h uuid/uuid.h mqueue.h
+
+for ac_header in sys/stat.h sys/ptrace.h sys/wait.h errno.h ctype.h process.h sys/mman.h uuid/uuid.h mqueue.h sys/sysctl.h
 do
 ac_safe=`echo "$ac_header" | sed 'y%./+-%__p_%'`
 echo "$as_me:$LINENO: checking for $ac_header" >&5
@@ -3370,7 +3425,7 @@ fi
 # If cpp failed, see if the compiler accepts the header.
 if test "$pac_found_header" != "yes" ; then
     cat >conftest.c<<EOF
-#line 3373 "configure"
+#line 3428 "configure"
 #include "confdefs.h"
 #include <$ac_header>
 int conftest() {return 0;}
@@ -3528,7 +3583,8 @@ done
 
 
 
-for ac_func in sysconf pthread_mutexattr_setpshared pthread_mutexattr_init
+
+for ac_func in sysconf sysctl pthread_mutexattr_setpshared pthread_mutexattr_init
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
 echo "$as_me:$LINENO: checking for $ac_func" >&5
@@ -3872,7 +3928,7 @@ fi
 # If cpp failed, see if the compiler accepts the header.
 if test "$pac_found_header" != "yes" ; then
     cat >conftest.c<<EOF
-#line 3875 "configure"
+#line 3931 "configure"
 #include "confdefs.h"
 #include <$ac_header>
 int conftest() {return 0;}
@@ -3963,7 +4019,7 @@ fi
 # If cpp failed, see if the compiler accepts the header.
 if test "$pac_found_header" != "yes" ; then
     cat >conftest.c<<EOF
-#line 3966 "configure"
+#line 4022 "configure"
 #include "confdefs.h"
 #include <$ac_header>
 int conftest() {return 0;}
@@ -4950,10 +5006,13 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 #include <sys/shm.h>
-key_t key = rand();
-int id = shmget(key,128,IPC_CREAT);
-if (id) shmctl(id,IPC_RMID,0);
-return (id > 0) ? 0 : 1;
+int main(int argc, char *argv[])
+{
+   key_t key = rand();
+   int id = shmget(key,128,IPC_CREAT);
+   if (id) shmctl(id,IPC_RMID,0);
+   return (id > 0) ? 0 : 1;
+}
 
 _ACEOF
 rm -f conftest$ac_exeext
@@ -5577,6 +5636,9 @@ fi
 SSM_LIBS=$LIBS
 LIBS=$save_libs
 
+# We need the util/sock/ch3usock.h header file
+CPPFLAGS="${CPPFLAGS} -I${master_top_srcdir}/src/mpid/ch3/util/sock"
+
 
 
 
@@ -5600,6 +5662,23 @@ echo "$as_me: WARNING: libtool selected for shared library support but LIBTOOL i
 
 
 
+
+
+
+
+export ETAGS
+export ETAGSADD
+
+
+if test -n "$CONF_BASE_CACHEFILE" -a -s "$CONF_BASE_CACHEFILE" ; then
+    set | grep ac_cv > $CONF_BASE_CACHEFILE.new
+    if cmp -s $CONF_BASE_CACHEFILE.new $CONF_BASE_CACHEFILE ; then
+	:
+    else
+	echo "Replacing $CONF_BASE_CACHEFILE"
+	mv $CONF_BASE_CACHEFILE.new $CONF_BASE_CACHEFILE
+    fi
+fi
 
 
                               ac_config_files="$ac_config_files Makefile src/Makefile localdefs"
@@ -6241,6 +6320,8 @@ s,@ENABLE_SHLIB@,$ENABLE_SHLIB,;t t
 s,@master_top_srcdir@,$master_top_srcdir,;t t
 s,@master_top_builddir@,$master_top_builddir,;t t
 s,@MAKE_DEPEND_C@,$MAKE_DEPEND_C,;t t
+s,@ETAGS@,$ETAGS,;t t
+s,@ETAGSADD@,$ETAGSADD,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
diff --git a/src/mpid/common/locks/configure b/src/mpid/common/locks/configure
--- a/src/mpid/common/locks/configure
+++ b/src/mpid/common/locks/configure
@@ -1381,16 +1381,61 @@ ac_configure=$ac_aux_dir/configure # This should be Cygnus configure.
 
 
 
+
+
+
+
 echo "RUNNING CONFIGURE FOR LOCKS"
 
-if test "`cd $srcdir && pwd`" != "`pwd`" && \
-   test -f $srcdir/config.status ; then
-    { { echo "$as_me:$LINENO: error: You cannot do a VPATH build if the source directory has been
-    configured.  Run \"make distclean\" in $srcdir first." >&5
+
+rm -f conftest*
+date >conftest$$
+# If creating a file in the current directory does not show up in the srcdir
+# then we're doing a VPATH build (or something is very wrong)
+if test ! -s $srcdir/conftest$$ ; then
+    pac_dirtyfiles=""
+    pac_dirtydirs=""
+    pac_header=""
+
+    for file in config.status $pac_header  ; do
+        if test -f $srcdir/$file ; then
+	    pac_dirtyfiles="$pac_dirtyfiles $file"
+	fi
+    done
+
+
+    if test -n "$pac_dirtyfiles" -o -n "$pac_dirtydirs" ; then
+	# Create a nice message about what to remove
+	rmmsg=""
+	if test -n "$pac_dirtyfiles" ; then
+	    rmmsg="files $pac_dirtyfiles"
+        fi
+ 	if test -n "$pac_dirtydirs" ; then
+	    if test -n "$rmmsg" ; then
+	        rmmsg="$rmmsg and directories $pac_dirtydirs"
+            else
+                rmmsg="directories $pac_dirtydirs"
+            fi
+        fi
+        if test -f $srcdir/Makefile ; then
+            { { echo "$as_me:$LINENO: error: You cannot do a VPATH build if the source directory has been
+    configured.  Run \"make distclean\" in $srcdir first and make sure that the
+    $rmmsg have been removed." >&5
 echo "$as_me: error: You cannot do a VPATH build if the source directory has been
-    configured.  Run \"make distclean\" in $srcdir first." >&2;}
+    configured.  Run \"make distclean\" in $srcdir first and make sure that the
+    $rmmsg have been removed." >&2;}
    { (exit 1); exit 1; }; }
+        else
+            { { echo "$as_me:$LINENO: error: You cannot do a VPATH build if the source directory has been
+    configured.  Remove the $rmmsg in $srcdir." >&5
+echo "$as_me: error: You cannot do a VPATH build if the source directory has been
+    configured.  Remove the $rmmsg in $srcdir." >&2;}
+   { (exit 1); exit 1; }; }
+        fi
+    fi
 fi
+rm -f conftest*
+
 
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
@@ -2912,7 +2957,7 @@ fi
 # If cpp failed, see if the compiler accepts the header.
 if test "$pac_found_header" != "yes" ; then
     cat >conftest.c<<EOF
-#line 2915 "configure"
+#line 2960 "configure"
 #include "confdefs.h"
 #include <$ac_header>
 int conftest() {return 0;}
@@ -2958,6 +3003,13 @@ cat >>confdefs.h <<\_ACEOF
 #define HAVE_SPARC_INLINE_PROCESS_LOCKS 1
 _ACEOF
 
+    # The current code design adds a .il file to CFLAGS, which (a) doesn't
+    # always reach all of the necessary files (I saw failures in ch3_progress.c
+    # where the inline file was not in the Makefile) and (a) adds the inline
+    # where it should not be, such as in mpicc.
+    { { echo "$as_me:$LINENO: error: Use of inline process locks is not supported.  Please volunteer to fix this code" >&5
+echo "$as_me: error: Use of inline process locks is not supported.  Please volunteer to fix this code" >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 
diff --git a/src/mpid/common/sock/configure b/src/mpid/common/sock/configure
--- a/src/mpid/common/sock/configure
+++ b/src/mpid/common/sock/configure
@@ -1350,16 +1350,69 @@ ac_configure=$ac_aux_dir/configure # This should be Cygnus configure.
 
 
 
+
+
+
+
 echo "RUNNING CONFIGURE FOR THE SOCK INTERFACE"
 
-if test "`cd $srcdir && pwd`" != "`pwd`" && \
-   test -f $srcdir/config.status ; then
-    { { echo "$as_me:$LINENO: error: You cannot do a VPATH build if the source directory has been
-    configured.  Run \"make distclean\" in $srcdir first." >&5
+
+rm -f conftest*
+date >conftest$$
+# If creating a file in the current directory does not show up in the srcdir
+# then we're doing a VPATH build (or something is very wrong)
+if test ! -s $srcdir/conftest$$ ; then
+    pac_dirtyfiles=""
+    pac_dirtydirs=""
+    pac_header=""
+
+    for file in config.status $pac_header  ; do
+        if test -f $srcdir/$file ; then
+	    pac_dirtyfiles="$pac_dirtyfiles $file"
+	fi
+    done
+
+
+    if test -n "$pac_dirtyfiles" -o -n "$pac_dirtydirs" ; then
+	# Create a nice message about what to remove
+	rmmsg=""
+	if test -n "$pac_dirtyfiles" ; then
+	    rmmsg="files $pac_dirtyfiles"
+        fi
+ 	if test -n "$pac_dirtydirs" ; then
+	    if test -n "$rmmsg" ; then
+	        rmmsg="$rmmsg and directories $pac_dirtydirs"
+            else
+                rmmsg="directories $pac_dirtydirs"
+            fi
+        fi
+        if test -f $srcdir/Makefile ; then
+            { { echo "$as_me:$LINENO: error: You cannot do a VPATH build if the source directory has been
+    configured.  Run \"make distclean\" in $srcdir first and make sure that the
+    $rmmsg have been removed." >&5
 echo "$as_me: error: You cannot do a VPATH build if the source directory has been
-    configured.  Run \"make distclean\" in $srcdir first." >&2;}
+    configured.  Run \"make distclean\" in $srcdir first and make sure that the
+    $rmmsg have been removed." >&2;}
    { (exit 1); exit 1; }; }
+        else
+            { { echo "$as_me:$LINENO: error: You cannot do a VPATH build if the source directory has been
+    configured.  Remove the $rmmsg in $srcdir." >&5
+echo "$as_me: error: You cannot do a VPATH build if the source directory has been
+    configured.  Remove the $rmmsg in $srcdir." >&2;}
+   { (exit 1); exit 1; }; }
+        fi
+    fi
 fi
+rm -f conftest*
+
+
+
+if test -n "$CONF_BASE_CACHEFILE" -a -s "$CONF_BASE_CACHEFILE" ; then
+    echo "Loading base cachefile $CONF_BASE_CACHEFILE"
+    . $CONF_BASE_CACHEFILE
+    export CONF_BASE_CACHEFILE
+fi
+
 
 . ${master_top_srcdir}/src/mpid/common/sock/setup.args
 export sock_name
@@ -1662,6 +1715,7 @@ fi
 
 export ETAGS
 export ETAGSADD
+
 
 
 
diff --git a/src/mpid/common/sock/poll/configure b/src/mpid/common/sock/poll/configure
--- a/src/mpid/common/sock/poll/configure
+++ b/src/mpid/common/sock/poll/configure
@@ -803,6 +803,7 @@ if test -n "$ac_init_help"; then
 Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
+--enable-sock-debug - Turn on tests of the socket data structures
 --enable-echo - turn on echoing from within configure script
 
 Some influential environment variables:
@@ -1382,7 +1383,19 @@ ac_config_sub=$ac_aux_dir/config.sub
 ac_configure=$ac_aux_dir/configure # This should be Cygnus configure.
 
 
+# Check whether --enable-sock-debug or --disable-sock-debug was given.
+if test "${enable_sock_debug+set}" = set; then
+  enableval="$enable_sock_debug"
+
+else
+  enable_sock_debug=no
+fi;
+
           ac_config_headers="$ac_config_headers mpidu_socki_conf.h"
+
+
+
+
 
 
 echo "RUNNING CONFIGURE FOR THE POLL IMPLEMENTATION OF SOCK"
@@ -1393,12 +1406,70 @@ if test "${enable_echo+set}" = set; then
   set -x
 fi;
 
-if test "`cd $srcdir && pwd`" != "`pwd`" && test -f $srcdir/config.status ; then
-    { { echo "$as_me:$LINENO: error: You cannot do a VPATH build if the source directory has been
-    configured.  Run \"make distclean\" in $srcdir first." >&5
+
+rm -f conftest*
+date >conftest$$
+# If creating a file in the current directory does not show up in the srcdir
+# then we're doing a VPATH build (or something is very wrong)
+if test ! -s $srcdir/conftest$$ ; then
+    pac_dirtyfiles=""
+    pac_dirtydirs=""
+    pac_header=""
+
+    for file in config.status $pac_header  ; do
+        if test -f $srcdir/$file ; then
+	    pac_dirtyfiles="$pac_dirtyfiles $file"
+	fi
+    done
+
+
+    if test -n "$pac_dirtyfiles" -o -n "$pac_dirtydirs" ; then
+	# Create a nice message about what to remove
+	rmmsg=""
+	if test -n "$pac_dirtyfiles" ; then
+	    rmmsg="files $pac_dirtyfiles"
+        fi
+ 	if test -n "$pac_dirtydirs" ; then
+	    if test -n "$rmmsg" ; then
+	        rmmsg="$rmmsg and directories $pac_dirtydirs"
+            else
+                rmmsg="directories $pac_dirtydirs"
+            fi
+        fi
+        if test -f $srcdir/Makefile ; then
+            { { echo "$as_me:$LINENO: error: You cannot do a VPATH build if the source directory has been
+    configured.  Run \"make distclean\" in $srcdir first and make sure that the
+    $rmmsg have been removed." >&5
 echo "$as_me: error: You cannot do a VPATH build if the source directory has been
-    configured.  Run \"make distclean\" in $srcdir first." >&2;}
+    configured.  Run \"make distclean\" in $srcdir first and make sure that the
+    $rmmsg have been removed." >&2;}
    { (exit 1); exit 1; }; }
+        else
+            { { echo "$as_me:$LINENO: error: You cannot do a VPATH build if the source directory has been
+    configured.  Remove the $rmmsg in $srcdir." >&5
+echo "$as_me: error: You cannot do a VPATH build if the source directory has been
+    configured.  Remove the $rmmsg in $srcdir." >&2;}
+   { (exit 1); exit 1; }; }
+        fi
+    fi
+fi
+rm -f conftest*
+
+
+
+if test -n "$CONF_BASE_CACHEFILE" -a -s "$CONF_BASE_CACHEFILE" ; then
+    echo "Loading base cachefile $CONF_BASE_CACHEFILE"
+    . $CONF_BASE_CACHEFILE
+    export CONF_BASE_CACHEFILE
+fi
+
+
+if test "$enable_sock_debug" = yes ; then
+
+cat >>confdefs.h <<\_ACEOF
+#define USE_SOCK_VERIFY 1
+_ACEOF
+
 fi
 
 
@@ -3077,7 +3148,7 @@ fi
 # If cpp failed, see if the compiler accepts the header.
 if test "$pac_found_header" != "yes" ; then
     cat >conftest.c<<EOF
-#line 3080 "configure"
+#line 3151 "configure"
 #include "confdefs.h"
 #include <$ac_header>
 int conftest() {return 0;}
@@ -3738,70 +3809,8 @@ fi
 TCP_LIBS="$TCP_LIBS $LIBS"
 LIBS="$saveLIBS $LIBS"
 #
-# Check for socklen_t .  If undefined, define it as int
-echo "$as_me:$LINENO: checking whether socklen_t is defined" >&5
-echo $ECHO_N "checking whether socklen_t is defined... $ECHO_C" >&6
-if test "${pac_cv_have_socklen_t+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-#include <sys/types.h>
-#include <sys/socket.h>
-typedef double socklen_t;
-int
-main ()
-{
-socklen_t a;
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext
-if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-  (eval $ac_compile) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest.$ac_objext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  pac_cv_have_socklen_t=no
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-pac_cv_have_socklen_t=yes
-fi
-rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
-fi
-echo "$as_me:$LINENO: result: $pac_cv_have_socklen_t" >&5
-echo "${ECHO_T}$pac_cv_have_socklen_t" >&6
-if test "$pac_cv_have_socklen_t" = no ; then
-
-cat >>confdefs.h <<\_ACEOF
-#define socklen_t int
-_ACEOF
-
-fi
+# Check first for sys/socket.h .  We check not only for existence but whether
+# it can be compiled (!), as we have seen some problems with this.
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -3853,6 +3862,74 @@ if test "$ac_cv_header_sys_socket_h" = yes ; then
 
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_SYS_SOCKET_H 1
+_ACEOF
+
+fi
+# Check for socklen_t .  If undefined, define it as int
+# (note the conditional inclusion of sys/socket.h)
+echo "$as_me:$LINENO: checking whether socklen_t is defined (in sys/socket.h if present)" >&5
+echo $ECHO_N "checking whether socklen_t is defined (in sys/socket.h if present)... $ECHO_C" >&6
+if test "${pac_cv_have_socklen_t+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#include <sys/types.h>
+#ifdef HAVE_SYS_SOCKET_H
+#include <sys/socket.h>
+#endif
+
+typedef struct { double a; int b; } socklen_t;
+int
+main ()
+{
+socklen_t a;a.a=1.0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  pac_cv_have_socklen_t=no
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+pac_cv_have_socklen_t=yes
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $pac_cv_have_socklen_t" >&5
+echo "${ECHO_T}$pac_cv_have_socklen_t" >&6
+if test "$pac_cv_have_socklen_t" = no ; then
+
+cat >>confdefs.h <<\_ACEOF
+#define socklen_t int
 _ACEOF
 
 fi
@@ -3924,6 +4001,17 @@ test -n "$ETAGS" || ETAGS="true"
 
 export ETAGS
 export ETAGSADD
+
+
+if test -n "$CONF_BASE_CACHEFILE" -a -s "$CONF_BASE_CACHEFILE" ; then
+    set | grep ac_cv > $CONF_BASE_CACHEFILE.new
+    if cmp -s $CONF_BASE_CACHEFILE.new $CONF_BASE_CACHEFILE ; then
+	:
+    else
+	echo "Replacing $CONF_BASE_CACHEFILE"
+	mv $CONF_BASE_CACHEFILE.new $CONF_BASE_CACHEFILE
+    fi
+fi
 
 
                     ac_config_files="$ac_config_files Makefile localdefs"
diff --git a/src/pm/gforker/configure b/src/pm/gforker/configure
--- a/src/pm/gforker/configure
+++ b/src/pm/gforker/configure
@@ -807,6 +807,7 @@ Optional Features:
 --enable-cache  - Turn on configure caching
 --enable-echo  - Turn on strong echoing. The default is enable=no.
 --enable-strict - Turn on strict debugging with gcc
+--enable-allowport - Turn on use of a port for communicating with the processes started by mpiexec
 --enable-g=option - Control the level of debugging support in the PMI
 implementation.  option may be a list of common separated names including
     none  - No debugging
@@ -1364,6 +1365,10 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
           ac_config_headers="$ac_config_headers forkerconf.h"
 
+
+
+
+
 if test -f $CONFIG_AUX_DIR/install-sh ; then ac_aux_dir=$CONFIG_AUX_DIR
 else
 ac_aux_dir=
@@ -1415,6 +1420,13 @@ if test "${enable_strict+set}" = set; then
 else
   enable_strict=no
 fi;
+# Check whether --enable-allowport or --disable-allowport was given.
+if test "${enable_allowport+set}" = set; then
+  enableval="$enable_allowport"
+
+else
+  enable_allowport=yes
+fi;
 # Check whether --enable-g or --disable-g was given.
 if test "${enable_g+set}" = set; then
   enableval="$enable_g"
@@ -1436,13 +1448,55 @@ if test "${enable_newsession+set}" = set; then
 else
   enable_newsession=yes
 fi;
-if test "`cd $srcdir && pwd`" != "`pwd`" && test -f $srcdir/config.status ; then
-    { { echo "$as_me:$LINENO: error: You cannot do a VPATH build if the source directory has been
-    configured.  Run \"make distclean\" in $srcdir first." >&5
+
+rm -f conftest*
+date >conftest$$
+# If creating a file in the current directory does not show up in the srcdir
+# then we're doing a VPATH build (or something is very wrong)
+if test ! -s $srcdir/conftest$$ ; then
+    pac_dirtyfiles=""
+    pac_dirtydirs=""
+    pac_header=""
+
+    for file in config.status $pac_header  ; do
+        if test -f $srcdir/$file ; then
+	    pac_dirtyfiles="$pac_dirtyfiles $file"
+	fi
+    done
+
+
+    if test -n "$pac_dirtyfiles" -o -n "$pac_dirtydirs" ; then
+	# Create a nice message about what to remove
+	rmmsg=""
+	if test -n "$pac_dirtyfiles" ; then
+	    rmmsg="files $pac_dirtyfiles"
+        fi
+ 	if test -n "$pac_dirtydirs" ; then
+	    if test -n "$rmmsg" ; then
+	        rmmsg="$rmmsg and directories $pac_dirtydirs"
+            else
+                rmmsg="directories $pac_dirtydirs"
+            fi
+        fi
+        if test -f $srcdir/Makefile ; then
+            { { echo "$as_me:$LINENO: error: You cannot do a VPATH build if the source directory has been
+    configured.  Run \"make distclean\" in $srcdir first and make sure that the
+    $rmmsg have been removed." >&5
 echo "$as_me: error: You cannot do a VPATH build if the source directory has been
-    configured.  Run \"make distclean\" in $srcdir first." >&2;}
+    configured.  Run \"make distclean\" in $srcdir first and make sure that the
+    $rmmsg have been removed." >&2;}
    { (exit 1); exit 1; }; }
+        else
+            { { echo "$as_me:$LINENO: error: You cannot do a VPATH build if the source directory has been
+    configured.  Remove the $rmmsg in $srcdir." >&5
+echo "$as_me: error: You cannot do a VPATH build if the source directory has been
+    configured.  Remove the $rmmsg in $srcdir." >&2;}
+   { (exit 1); exit 1; }; }
+        fi
+    fi
 fi
+rm -f conftest*
+
 # enable-g
 # strip off multiple options, separated by commas
 save_IFS="$IFS"
@@ -1466,6 +1520,15 @@ if test -z "$top_srcdir" ; then
 else
    use_top_srcdir=$top_srcdir
 fi
+
+
+if test -n "$CONF_BASE_CACHEFILE" -a -s "$CONF_BASE_CACHEFILE" ; then
+    echo "Loading base cachefile $CONF_BASE_CACHEFILE"
+    . $CONF_BASE_CACHEFILE
+    export CONF_BASE_CACHEFILE
+fi
+
+
 
 
 ac_ext=c
@@ -3120,7 +3183,8 @@ case "$ENABLE_SHLIB" in
     # We need to panic; -static won't work on OS/X.
     ;;
     gcc)
-    LDFLAGS="$LDFLAGS -static"
+    # Gahh.  Gcc even complains about this now.
+    #LDFLAGS="$LDFLAGS -static"
     ;;
     solaris)
     # Gahh.  We'd like to use -Bstatic, but on some of our Solaris systems,
@@ -4861,7 +4925,7 @@ fi
 # If cpp failed, see if the compiler accepts the header.
 if test "$pac_found_header" != "yes" ; then
     cat >conftest.c<<EOF
-#line 4864 "configure"
+#line 4928 "configure"
 #include "confdefs.h"
 #include <$ac_header>
 int conftest() {return 0;}
@@ -5104,9 +5168,14 @@ _ACEOF
 fi
 done
 
+sigaction_ok=no
 if test "$ac_cv_func_sigaction" = "yes" ; then
     echo "$as_me:$LINENO: checking for struct sigaction" >&5
 echo $ECHO_N "checking for struct sigaction... $ECHO_C" >&6
+if test "${pac_cv_struct_sigaction+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
     cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -5144,19 +5213,24 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  sigaction_ok="yes"
+  pac_cv_struct_sigaction="yes"
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-sigaction_ok="no"
+pac_cv_struct_sigaction="no"
 fi
 rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
-    echo "$as_me:$LINENO: result: $sigaction_ok" >&5
-echo "${ECHO_T}$sigaction_ok" >&6
-    if test "$sigaction_ok" = "no" ; then
+fi
+echo "$as_me:$LINENO: result: $pac_cv_struct_sigaction" >&5
+echo "${ECHO_T}$pac_cv_struct_sigaction" >&6
+    if test "$pac_cv_struct_sigaction" = "no" ; then
         echo "$as_me:$LINENO: checking for struct sigaction with _POSIX_SOURCE" >&5
 echo $ECHO_N "checking for struct sigaction with _POSIX_SOURCE... $ECHO_C" >&6
+if test "${pac_cv_struct_sigaction_needs_posix+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
         cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -5195,25 +5269,27 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  sigaction_with_posix_ok="yes"
+  pac_cv_struct_sigaction_needs_posix="yes"
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-sigaction_with_posix_ok="no"
+pac_cv_struct_sigaction_needs_posix="no"
 fi
 rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
-        echo "$as_me:$LINENO: result: $sigaction_with_posix_ok" >&5
-echo "${ECHO_T}$sigaction_with_posix_ok" >&6
-        if test "$sigaction_with_posix_ok" = "yes" ; then
+fi
+echo "$as_me:$LINENO: result: $pac_cv_struct_sigaction_needs_posix" >&5
+echo "${ECHO_T}$pac_cv_struct_sigaction_needs_posix" >&6
+        if test "$pac_cv_struct_sigaction_needs_posix" = "yes" ; then
             sigaction_ok=yes
-	    sigaction_needs_posix=yes
 	fi
+    else
+        sigaction_ok=yes
     fi
 fi
 # Decide on the signal handler to use
 if test "$ac_cv_func_sigaction" = "yes" -a "$sigaction_ok" = "yes" ; then
-    if test "$sigaction_needs_posix" = yes ; then
+    if test "$pac_struct_sigaction_needs_posix" = yes ; then
 
 cat >>confdefs.h <<\_ACEOF
 #define NEEDS_POSIX_FOR_SIGACTION 1
@@ -5229,6 +5305,13 @@ elif test "$ac_cv_func_signal" = "yes" ; then
 
 cat >>confdefs.h <<\_ACEOF
 #define USE_SIGNAL 1
+_ACEOF
+
+fi
+if test "$enable_allowport" = "yes" ; then
+
+cat >>confdefs.h <<\_ACEOF
+#define MPIEXEC_ALLOW_PORT 1
 _ACEOF
 
 fi
@@ -5295,7 +5378,7 @@ fi
 # If cpp failed, see if the compiler accepts the header.
 if test "$pac_found_header" != "yes" ; then
     cat >conftest.c<<EOF
-#line 5298 "configure"
+#line 5381 "configure"
 #include "confdefs.h"
 #include <$ac_header>
 int conftest() {return 0;}
@@ -5350,6 +5433,19 @@ fi
 
 export ETAGS
 export ETAGSADD
+
+
+
+if test -n "$CONF_BASE_CACHEFILE" -a -s "$CONF_BASE_CACHEFILE" ; then
+    set | grep ac_cv > $CONF_BASE_CACHEFILE.new
+    if cmp -s $CONF_BASE_CACHEFILE.new $CONF_BASE_CACHEFILE ; then
+	:
+    else
+	echo "Replacing $CONF_BASE_CACHEFILE"
+	mv $CONF_BASE_CACHEFILE.new $CONF_BASE_CACHEFILE
+    fi
+fi
+
 
           ac_config_files="$ac_config_files Makefile"
 cat >confcache <<\_ACEOF
diff --git a/src/pm/smpd/configure b/src/pm/smpd/configure
--- a/src/pm/smpd/configure
+++ b/src/pm/smpd/configure
@@ -1359,6 +1359,10 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
           ac_config_headers="$ac_config_headers smpdconf.h"
 
+
+
+
+
 if test -f $CONFIG_AUX_DIR/install-sh ; then ac_aux_dir=$CONFIG_AUX_DIR
 else
 ac_aux_dir=
@@ -1415,13 +1419,55 @@ if test "${enable_g+set}" = set; then
 else
   enable_g=none
 fi;
-if test "`cd $srcdir && pwd`" != "`pwd`" && test -f $srcdir/config.status ; then
-    { { echo "$as_me:$LINENO: error: You cannot do a VPATH build if the source directory has been
-    configured.  Run \"make distclean\" in $srcdir first." >&5
+
+rm -f conftest*
+date >conftest$$
+# If creating a file in the current directory does not show up in the srcdir
+# then we're doing a VPATH build (or something is very wrong)
+if test ! -s $srcdir/conftest$$ ; then
+    pac_dirtyfiles=""
+    pac_dirtydirs=""
+    pac_header=""
+
+    for file in config.status $pac_header  ; do
+        if test -f $srcdir/$file ; then
+	    pac_dirtyfiles="$pac_dirtyfiles $file"
+	fi
+    done
+
+
+    if test -n "$pac_dirtyfiles" -o -n "$pac_dirtydirs" ; then
+	# Create a nice message about what to remove
+	rmmsg=""
+	if test -n "$pac_dirtyfiles" ; then
+	    rmmsg="files $pac_dirtyfiles"
+        fi
+ 	if test -n "$pac_dirtydirs" ; then
+	    if test -n "$rmmsg" ; then
+	        rmmsg="$rmmsg and directories $pac_dirtydirs"
+            else
+                rmmsg="directories $pac_dirtydirs"
+            fi
+        fi
+        if test -f $srcdir/Makefile ; then
+            { { echo "$as_me:$LINENO: error: You cannot do a VPATH build if the source directory has been
+    configured.  Run \"make distclean\" in $srcdir first and make sure that the
+    $rmmsg have been removed." >&5
 echo "$as_me: error: You cannot do a VPATH build if the source directory has been
-    configured.  Run \"make distclean\" in $srcdir first." >&2;}
+    configured.  Run \"make distclean\" in $srcdir first and make sure that the
+    $rmmsg have been removed." >&2;}
    { (exit 1); exit 1; }; }
+        else
+            { { echo "$as_me:$LINENO: error: You cannot do a VPATH build if the source directory has been
+    configured.  Remove the $rmmsg in $srcdir." >&5
+echo "$as_me: error: You cannot do a VPATH build if the source directory has been
+    configured.  Remove the $rmmsg in $srcdir." >&2;}
+   { (exit 1); exit 1; }; }
+        fi
+    fi
 fi
+rm -f conftest*
+
 case "$enable_g" in
     no|none)
     ;;
@@ -3636,7 +3682,7 @@ fi
 # If cpp failed, see if the compiler accepts the header.
 if test "$pac_found_header" != "yes" ; then
     cat >conftest.c<<EOF
-#line 3639 "configure"
+#line 3685 "configure"
 #include "confdefs.h"
 #include <$ac_header>
 int conftest() {return 0;}
@@ -3731,7 +3777,98 @@ fi
 # If cpp failed, see if the compiler accepts the header.
 if test "$pac_found_header" != "yes" ; then
     cat >conftest.c<<EOF
-#line 3734 "configure"
+#line 3780 "configure"
+#include "confdefs.h"
+#include <$ac_header>
+int conftest() {return 0;}
+EOF
+    ac_compile_for_cpp='${CC-cc} -c $CFLAGS $CPPFLAGS conftest.c 1>&5'
+    if { (eval echo "$as_me:$LINENO: \"$ac_compile_for_cpp\"") >&5
+  (eval $ac_compile_for_cpp) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+	pac_found_header=yes
+    else
+        echo "configure: failed program was:" >&5
+        cat conftest.c >&5
+    fi
+    rm -f conftest*
+fi
+# Finally, set the ac variable.
+if test "$pac_found_header" = "yes" ; then
+    eval "ac_cv_header_$ac_safe=yes"
+else
+    eval "ac_cv_header_$ac_safe=no"
+fi
+
+fi
+if eval "test \"`echo '$ac_cv_header_'$ac_safe`\" = yes"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+done
+
+
+
+
+for ac_header in stddef.h md5.h openssl/md5.h
+do
+ac_safe=`echo "$ac_header" | sed 'y%./+-%__p_%'`
+echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
+if eval "test \"\${ac_cv_header_$ac_safe+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+pac_found_header=no
+if test "$CPP" != "/lib/cpp" ; then
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <$ac_header>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+    ac_cpp_err=$ac_cpp_err$ac_c_werror_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  pac_found_header=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+rm -f conftest.err conftest.$ac_ext
+fi
+# If cpp failed, see if the compiler accepts the header.
+if test "$pac_found_header" != "yes" ; then
+    cat >conftest.c<<EOF
+#line 3871 "configure"
 #include "confdefs.h"
 #include <$ac_header>
 int conftest() {return 0;}
@@ -4207,6 +4344,109 @@ if test "$ac_cv_search_MD5" != no; then
 
 fi
 
+# Make configure check for MD5 so that the variable will be set
+
+for ac_func in MD5
+do
+as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $ac_func" >&5
+echo $ECHO_N "checking for $ac_func... $ECHO_C" >&6
+if eval "test \"\${$as_ac_var+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+/* Define $ac_func to an innocuous variant, in case <limits.h> declares $ac_func.
+   For example, HP-UX 11i <limits.h> declares gettimeofday.  */
+#define $ac_func innocuous_$ac_func
+
+/* System header to define __stub macros and hopefully few prototypes,
+    which can conflict with char $ac_func (); below.
+    Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
+    <limits.h> exists even on freestanding compilers.  */
+
+#ifdef __STDC__
+# include <limits.h>
+#else
+# include <assert.h>
+#endif
+
+#undef $ac_func
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+{
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char $ac_func ();
+/* The GNU C library defines this for functions which it implements
+    to always fail with ENOSYS.  Some functions are actually named
+    something starting with __ and the normal name is an alias.  */
+#if defined (__stub_$ac_func) || defined (__stub___$ac_func)
+choke me
+#else
+char (*f) () = $ac_func;
+#endif
+#ifdef __cplusplus
+}
+#endif
+
+int
+main ()
+{
+return f != $ac_func;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  eval "$as_ac_var=yes"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+eval "$as_ac_var=no"
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_var'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_var'}'`" >&6
+if test `eval echo '${'$as_ac_var'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_func" | $as_tr_cpp` 1
+_ACEOF
+
+fi
+done
+
+#
 echo "$as_me:$LINENO: checking for library containing md5_calc" >&5
 echo $ECHO_N "checking for library containing md5_calc... $ECHO_C" >&6
 if test "${ac_cv_search_md5_calc+set}" = set; then
@@ -4340,6 +4580,9 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 
+#ifdef HAVE_STDDEF_H
+ #include <stddef.h>
+#endif
 #include <md5.h>
 
 int
@@ -4394,7 +4637,16 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
-#AC_SEARCH_LIBS( MD5, crypto, SMPD_LIBS="$SMPD_LIBS -lcrypto" )
+# md5 appears to be required for SMPD.  Test that we have either mp5_calc
+# or MP5 (may be part of openssl/md5.h)
+if test "$ac_cv_have_md5_calc" != yes -a \
+  \( "$ac_cv_header_openssl_md5_h" != yes -o "$ac_cv_func_MD5" != yes \) ; then
+    { { echo "$as_me:$LINENO: error: SMPD requires MD5 support, and configure could not find either md5_calc in md5.h or MD5 in openssl/md5.h" >&5
+echo "$as_me: error: SMPD requires MD5 support, and configure could not find either md5_calc in md5.h or MD5 in openssl/md5.h" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
 SMPD_LIBS="$SMPD_LIBS $LIBS"
 
 
diff --git a/src/pmi/simple/configure b/src/pmi/simple/configure
--- a/src/pmi/simple/configure
+++ b/src/pmi/simple/configure
@@ -1355,6 +1355,10 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
           ac_config_headers="$ac_config_headers pmiconf.h"
 
+
+
+
+
 echo "RUNNING CONFIGURE FOR THE SIMPLE PMI"
 
 # Check whether --enable-cache or --disable-cache was given.
@@ -1376,6 +1380,64 @@ fi;
 if test "$enable_pmiport" != "no" ; then
    enable_pmiport=yes
 fi
+
+
+rm -f conftest*
+date >conftest$$
+# If creating a file in the current directory does not show up in the srcdir
+# then we're doing a VPATH build (or something is very wrong)
+if test ! -s $srcdir/conftest$$ ; then
+    pac_dirtyfiles=""
+    pac_dirtydirs=""
+    pac_header=""
+
+    for file in config.status $pac_header  ; do
+        if test -f $srcdir/$file ; then
+	    pac_dirtyfiles="$pac_dirtyfiles $file"
+	fi
+    done
+
+
+    if test -n "$pac_dirtyfiles" -o -n "$pac_dirtydirs" ; then
+	# Create a nice message about what to remove
+	rmmsg=""
+	if test -n "$pac_dirtyfiles" ; then
+	    rmmsg="files $pac_dirtyfiles"
+        fi
+ 	if test -n "$pac_dirtydirs" ; then
+	    if test -n "$rmmsg" ; then
+	        rmmsg="$rmmsg and directories $pac_dirtydirs"
+            else
+                rmmsg="directories $pac_dirtydirs"
+            fi
+        fi
+        if test -f $srcdir/Makefile ; then
+            { { echo "$as_me:$LINENO: error: You cannot do a VPATH build if the source directory has been
+    configured.  Run \"make distclean\" in $srcdir first and make sure that the
+    $rmmsg have been removed." >&5
+echo "$as_me: error: You cannot do a VPATH build if the source directory has been
+    configured.  Run \"make distclean\" in $srcdir first and make sure that the
+    $rmmsg have been removed." >&2;}
+   { (exit 1); exit 1; }; }
+        else
+            { { echo "$as_me:$LINENO: error: You cannot do a VPATH build if the source directory has been
+    configured.  Remove the $rmmsg in $srcdir." >&5
+echo "$as_me: error: You cannot do a VPATH build if the source directory has been
+    configured.  Remove the $rmmsg in $srcdir." >&2;}
+   { (exit 1); exit 1; }; }
+        fi
+    fi
+fi
+rm -f conftest*
+
+
+
+if test -n "$CONF_BASE_CACHEFILE" -a -s "$CONF_BASE_CACHEFILE" ; then
+    echo "Loading base cachefile $CONF_BASE_CACHEFILE"
+    . $CONF_BASE_CACHEFILE
+    export CONF_BASE_CACHEFILE
+fi
+
 
 
 true
@@ -2852,7 +2914,7 @@ fi
 # If cpp failed, see if the compiler accepts the header.
 if test "$pac_found_header" != "yes" ; then
     cat >conftest.c<<EOF
-#line 2855 "configure"
+#line 2917 "configure"
 #include "confdefs.h"
 #include <$ac_header>
 int conftest() {return 0;}
@@ -3133,7 +3195,7 @@ fi
 # If cpp failed, see if the compiler accepts the header.
 if test "$pac_found_header" != "yes" ; then
     cat >conftest.c<<EOF
-#line 3136 "configure"
+#line 3198 "configure"
 #include "confdefs.h"
 #include <$ac_header>
 int conftest() {return 0;}
@@ -3546,8 +3608,9 @@ echo "$as_me: error: Cannot build simple PMI with support for an IP port because
 fi
 
 # Check for socklen_t .  If undefined, define it as int
-echo "$as_me:$LINENO: checking whether socklen_t is defined" >&5
-echo $ECHO_N "checking whether socklen_t is defined... $ECHO_C" >&6
+# (note the conditional inclusion of sys/socket.h)
+echo "$as_me:$LINENO: checking whether socklen_t is defined (in sys/socket.h if present)" >&5
+echo $ECHO_N "checking whether socklen_t is defined (in sys/socket.h if present)... $ECHO_C" >&6
 if test "${pac_cv_have_socklen_t+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
@@ -3560,12 +3623,15 @@ cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 
 #include <sys/types.h>
+#ifdef HAVE_SYS_SOCKET_H
 #include <sys/socket.h>
-typedef double socklen_t;
+#endif
+
+typedef struct { double a; int b; } socklen_t;
 int
 main ()
 {
-socklen_t a;
+socklen_t a;a.a=1.0;
   ;
   return 0;
 }
@@ -3697,6 +3763,18 @@ echo "$as_me: WARNING: libtool selected for shared library support but LIBTOOL i
 
 export ETAGS
 export ETAGSADD
+
+
+
+if test -n "$CONF_BASE_CACHEFILE" -a -s "$CONF_BASE_CACHEFILE" ; then
+    set | grep ac_cv > $CONF_BASE_CACHEFILE.new
+    if cmp -s $CONF_BASE_CACHEFILE.new $CONF_BASE_CACHEFILE ; then
+	:
+    else
+	echo "Replacing $CONF_BASE_CACHEFILE"
+	mv $CONF_BASE_CACHEFILE.new $CONF_BASE_CACHEFILE
+    fi
+fi
 
 
                     ac_config_files="$ac_config_files Makefile localdefs"
diff --git a/src/pmi/uni/configure b/src/pmi/uni/configure
--- a/src/pmi/uni/configure
+++ b/src/pmi/uni/configure
@@ -1372,6 +1372,10 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
           ac_config_headers="$ac_config_headers pmiconf.h"
 
+
+
+
+
 echo "RUNNING CONFIGURE FOR THE UNI PMI"
 
 # Check whether --enable-cache or --disable-cache was given.
@@ -1413,13 +1417,55 @@ if test "${enable_g+set}" = set; then
 else
   enable_g=none
 fi;
-if test "`cd $srcdir && pwd`" != "`pwd`" && test -f $srcdir/config.status ; then
-    { { echo "$as_me:$LINENO: error: You cannot do a VPATH build if the source directory has been
-    configured.  Run \"make distclean\" in $srcdir first." >&5
+
+rm -f conftest*
+date >conftest$$
+# If creating a file in the current directory does not show up in the srcdir
+# then we're doing a VPATH build (or something is very wrong)
+if test ! -s $srcdir/conftest$$ ; then
+    pac_dirtyfiles=""
+    pac_dirtydirs=""
+    pac_header=""
+
+    for file in config.status $pac_header  ; do
+        if test -f $srcdir/$file ; then
+	    pac_dirtyfiles="$pac_dirtyfiles $file"
+	fi
+    done
+
+
+    if test -n "$pac_dirtyfiles" -o -n "$pac_dirtydirs" ; then
+	# Create a nice message about what to remove
+	rmmsg=""
+	if test -n "$pac_dirtyfiles" ; then
+	    rmmsg="files $pac_dirtyfiles"
+        fi
+ 	if test -n "$pac_dirtydirs" ; then
+	    if test -n "$rmmsg" ; then
+	        rmmsg="$rmmsg and directories $pac_dirtydirs"
+            else
+                rmmsg="directories $pac_dirtydirs"
+            fi
+        fi
+        if test -f $srcdir/Makefile ; then
+            { { echo "$as_me:$LINENO: error: You cannot do a VPATH build if the source directory has been
+    configured.  Run \"make distclean\" in $srcdir first and make sure that the
+    $rmmsg have been removed." >&5
 echo "$as_me: error: You cannot do a VPATH build if the source directory has been
-    configured.  Run \"make distclean\" in $srcdir first." >&2;}
+    configured.  Run \"make distclean\" in $srcdir first and make sure that the
+    $rmmsg have been removed." >&2;}
    { (exit 1); exit 1; }; }
+        else
+            { { echo "$as_me:$LINENO: error: You cannot do a VPATH build if the source directory has been
+    configured.  Remove the $rmmsg in $srcdir." >&5
+echo "$as_me: error: You cannot do a VPATH build if the source directory has been
+    configured.  Remove the $rmmsg in $srcdir." >&2;}
+   { (exit 1); exit 1; }; }
+        fi
+    fi
 fi
+rm -f conftest*
+
 case "$enable_error_checking" in
     no)
     ;;
@@ -3321,7 +3367,7 @@ fi
 # If cpp failed, see if the compiler accepts the header.
 if test "$pac_found_header" != "yes" ; then
     cat >conftest.c<<EOF
-#line 3324 "configure"
+#line 3370 "configure"
 #include "confdefs.h"
 #include <$ac_header>
 int conftest() {return 0;}
diff --git a/src/util/logging/rlog/configure b/src/util/logging/rlog/configure
--- a/src/util/logging/rlog/configure
+++ b/src/util/logging/rlog/configure
@@ -272,7 +272,7 @@ PACKAGE_STRING=
 PACKAGE_BUGREPORT=
 
 ac_unique_file="rlog.c"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS master_top_srcdir master_top_builddir CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT AR RANLIB MAKE VPATH SET_CFLAGS SET_MAKE CPP EGREP MPILIBNAME java_home java_arch CC_SHL C_LINK_SHL LIBTOOL ENABLE_SHLIB MAKE_DEPEND_C LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS master_top_srcdir master_top_builddir CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT AR RANLIB MAKE VPATH SET_CFLAGS SET_MAKE PERL CPP EGREP MPILIBNAME PMPILIBNAME java_home java_arch CC_SHL C_LINK_SHL LIBTOOL ENABLE_SHLIB MAKE_DEPEND_C ETAGS ETAGSADD DOCTEXT LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1363,6 +1363,10 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
           ac_config_headers="$ac_config_headers rlogconf.h"
 
+
+
+
+
 echo "RUNNING CONFIGURE FOR RLOG"
 
 # Check whether --enable-cache or --disable-cache was given.
@@ -1395,10 +1399,14 @@ if test "${enable_sharedlibs+set}" = set; then
   enableval="$enable_sharedlibs"
 
 fi;
-case "$enable_g" in
+# strip off multiple options, separated by commas
+save_IFS="$IFS"
+IFS=","
+for option in $enable_g ; do
+case "$option" in
     no|none)
     ;;
-    mem|all)
+    mem|all|yes)
 
 cat >>confdefs.h <<\_ACEOF
 #define USE_MEMORY_TRACING
@@ -1407,18 +1415,65 @@ _ACEOF
     enable_g_mem=yes
     CFLAGS="$CFLAGS -g"
     ;;
+    log|nesting|handle|debug|dbg)
+    # Ignore these (they are valid for other configures)
+    ;;
     *)
-    { echo "$as_me:$LINENO: WARNING: Unknown value $enable_g for enable-g" >&5
-echo "$as_me: WARNING: Unknown value $enable_g for enable-g" >&2;}
+    { echo "$as_me:$LINENO: WARNING: Unknown value $option for enable-g" >&5
+echo "$as_me: WARNING: Unknown value $option for enable-g" >&2;}
     ;;
 esac
-if test "`cd $srcdir && pwd`" != "`pwd`" && test -f $srcdir/config.status ; then
-    { { echo "$as_me:$LINENO: error: You cannot do a VPATH build if the source directory has been
-    configured.  Run \"make distclean\" in $srcdir first." >&5
+done
+IFS="$save_IFS"
+
+rm -f conftest*
+date >conftest$$
+# If creating a file in the current directory does not show up in the srcdir
+# then we're doing a VPATH build (or something is very wrong)
+if test ! -s $srcdir/conftest$$ ; then
+    pac_dirtyfiles=""
+    pac_dirtydirs=""
+    pac_header=""
+
+    for file in config.status $pac_header  ; do
+        if test -f $srcdir/$file ; then
+	    pac_dirtyfiles="$pac_dirtyfiles $file"
+	fi
+    done
+
+
+    if test -n "$pac_dirtyfiles" -o -n "$pac_dirtydirs" ; then
+	# Create a nice message about what to remove
+	rmmsg=""
+	if test -n "$pac_dirtyfiles" ; then
+	    rmmsg="files $pac_dirtyfiles"
+        fi
+ 	if test -n "$pac_dirtydirs" ; then
+	    if test -n "$rmmsg" ; then
+	        rmmsg="$rmmsg and directories $pac_dirtydirs"
+            else
+                rmmsg="directories $pac_dirtydirs"
+            fi
+        fi
+        if test -f $srcdir/Makefile ; then
+            { { echo "$as_me:$LINENO: error: You cannot do a VPATH build if the source directory has been
+    configured.  Run \"make distclean\" in $srcdir first and make sure that the
+    $rmmsg have been removed." >&5
 echo "$as_me: error: You cannot do a VPATH build if the source directory has been
-    configured.  Run \"make distclean\" in $srcdir first." >&2;}
+    configured.  Run \"make distclean\" in $srcdir first and make sure that the
+    $rmmsg have been removed." >&2;}
    { (exit 1); exit 1; }; }
+        else
+            { { echo "$as_me:$LINENO: error: You cannot do a VPATH build if the source directory has been
+    configured.  Remove the $rmmsg in $srcdir." >&5
+echo "$as_me: error: You cannot do a VPATH build if the source directory has been
+    configured.  Remove the $rmmsg in $srcdir." >&2;}
+   { (exit 1); exit 1; }; }
+        fi
+    fi
 fi
+rm -f conftest*
+
 
 if test -z "$top_srcdir" ; then
    use_top_srcdir=$srcdir
@@ -2703,6 +2758,45 @@ else
     SET_MAKE="MAKE=${MAKE-make}"
 fi
 
+# Extract the first word of "perl", so it can be a program name with args.
+set dummy perl; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_PERL+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $PERL in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PERL="$PERL" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_PERL="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+PERL=$ac_cv_path_PERL
+
+if test -n "$PERL"; then
+  echo "$as_me:$LINENO: result: $PERL" >&5
+echo "${ECHO_T}$PERL" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
 
 echo "$as_me:$LINENO: checking for an ANSI C-conforming const" >&5
 echo $ECHO_N "checking for an ANSI C-conforming const... $ECHO_C" >&6
@@ -3564,7 +3658,7 @@ fi
 # If cpp failed, see if the compiler accepts the header.
 if test "$pac_found_header" != "yes" ; then
     cat >conftest.c<<EOF
-#line 3567 "configure"
+#line 3661 "configure"
 #include "confdefs.h"
 #include <jni.h>
 int conftest() {return 0;}
@@ -3609,6 +3703,8 @@ echo "$as_me: WARNING: cannot compile trace code" >&2;}
 fi
 MPILIBNAME=${MPILIBNAME:-"mpich"}
 
+PMPILIBNAME=${PMPILIBNAME:-"p$MPILIBNAME"}
+
 
 java_home=/soft/com/packages/j2sdk1.4.0
 java_arch=linux
@@ -3636,7 +3732,13 @@ echo "$as_me: WARNING: libtool selected for shared library support but LIBTOOL i
 
 
 
-          ac_config_files="$ac_config_files Makefile"
+export ETAGS
+export ETAGSADD
+
+
+          ac_config_commands="$ac_config_commands default-1"
+
+                    ac_config_files="$ac_config_files Makefile pprintirlog"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -4054,6 +4156,9 @@ $config_files
 Configuration headers:
 $config_headers
 
+Configuration commands:
+$config_commands
+
 Report bugs to <bug-autoconf@gnu.org>."
 _ACEOF
 
@@ -4152,7 +4257,14 @@ fi
 
 _ACEOF
 
+cat >>$CONFIG_STATUS <<_ACEOF
+#
+# INIT-COMMANDS section.
+#
 
+
+
+_ACEOF
 
 
 
@@ -4162,6 +4274,8 @@ do
   case "$ac_config_target" in
   # Handling of arguments.
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
+  "pprintirlog" ) CONFIG_FILES="$CONFIG_FILES pprintirlog" ;;
+  "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "rlogconf.h" ) CONFIG_HEADERS="$CONFIG_HEADERS rlogconf.h" ;;
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
@@ -4176,6 +4290,7 @@ done
 if $ac_need_defaults; then
   test "${CONFIG_FILES+set}" = set || CONFIG_FILES=$config_files
   test "${CONFIG_HEADERS+set}" = set || CONFIG_HEADERS=$config_headers
+  test "${CONFIG_COMMANDS+set}" = set || CONFIG_COMMANDS=$config_commands
 fi
 
 # Have a temporary directory for convenience.  Make it in the build tree
@@ -4262,9 +4377,11 @@ s,@MAKE@,$MAKE,;t t
 s,@VPATH@,$VPATH,;t t
 s,@SET_CFLAGS@,$SET_CFLAGS,;t t
 s,@SET_MAKE@,$SET_MAKE,;t t
+s,@PERL@,$PERL,;t t
 s,@CPP@,$CPP,;t t
 s,@EGREP@,$EGREP,;t t
 s,@MPILIBNAME@,$MPILIBNAME,;t t
+s,@PMPILIBNAME@,$PMPILIBNAME,;t t
 s,@java_home@,$java_home,;t t
 s,@java_arch@,$java_arch,;t t
 s,@CC_SHL@,$CC_SHL,;t t
@@ -4272,6 +4389,9 @@ s,@C_LINK_SHL@,$C_LINK_SHL,;t t
 s,@LIBTOOL@,$LIBTOOL,;t t
 s,@ENABLE_SHLIB@,$ENABLE_SHLIB,;t t
 s,@MAKE_DEPEND_C@,$MAKE_DEPEND_C,;t t
+s,@ETAGS@,$ETAGS,;t t
+s,@ETAGSADD@,$ETAGSADD,;t t
+s,@DOCTEXT@,$DOCTEXT,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
@@ -4731,6 +4851,124 @@ echo "$as_me: error: cannot create directory \"$ac_dir\"" >&2;}
   fi
 done
 _ACEOF
+cat >>$CONFIG_STATUS <<\_ACEOF
+
+#
+# CONFIG_COMMANDS section.
+#
+for ac_file in : $CONFIG_COMMANDS; do test "x$ac_file" = x: && continue
+  ac_dest=`echo "$ac_file" | sed 's,:.*,,'`
+  ac_source=`echo "$ac_file" | sed 's,[^:]*:,,'`
+  ac_dir=`(dirname "$ac_dest") 2>/dev/null ||
+$as_expr X"$ac_dest" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
+	 X"$ac_dest" : 'X\(//\)[^/]' \| \
+	 X"$ac_dest" : 'X\(//\)$' \| \
+	 X"$ac_dest" : 'X\(/\)' \| \
+	 .     : '\(.\)' 2>/dev/null ||
+echo X"$ac_dest" |
+    sed '/^X\(.*[^/]\)\/\/*[^/][^/]*\/*$/{ s//\1/; q; }
+  	  /^X\(\/\/\)[^/].*/{ s//\1/; q; }
+  	  /^X\(\/\/\)$/{ s//\1/; q; }
+  	  /^X\(\/\).*/{ s//\1/; q; }
+  	  s/.*/./; q'`
+  { if $as_mkdir_p; then
+    mkdir -p "$ac_dir"
+  else
+    as_dir="$ac_dir"
+    as_dirs=
+    while test ! -d "$as_dir"; do
+      as_dirs="$as_dir $as_dirs"
+      as_dir=`(dirname "$as_dir") 2>/dev/null ||
+$as_expr X"$as_dir" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
+	 X"$as_dir" : 'X\(//\)[^/]' \| \
+	 X"$as_dir" : 'X\(//\)$' \| \
+	 X"$as_dir" : 'X\(/\)' \| \
+	 .     : '\(.\)' 2>/dev/null ||
+echo X"$as_dir" |
+    sed '/^X\(.*[^/]\)\/\/*[^/][^/]*\/*$/{ s//\1/; q; }
+  	  /^X\(\/\/\)[^/].*/{ s//\1/; q; }
+  	  /^X\(\/\/\)$/{ s//\1/; q; }
+  	  /^X\(\/\).*/{ s//\1/; q; }
+  	  s/.*/./; q'`
+    done
+    test ! -n "$as_dirs" || mkdir $as_dirs
+  fi || { { echo "$as_me:$LINENO: error: cannot create directory \"$ac_dir\"" >&5
+echo "$as_me: error: cannot create directory \"$ac_dir\"" >&2;}
+   { (exit 1); exit 1; }; }; }
+
+  ac_builddir=.
+
+if test "$ac_dir" != .; then
+  ac_dir_suffix=/`echo "$ac_dir" | sed 's,^\.[\\/],,'`
+  # A "../" for each directory in $ac_dir_suffix.
+  ac_top_builddir=`echo "$ac_dir_suffix" | sed 's,/[^\\/]*,../,g'`
+else
+  ac_dir_suffix= ac_top_builddir=
+fi
+
+case $srcdir in
+  .)  # No --srcdir option.  We are building in place.
+    ac_srcdir=.
+    if test -z "$ac_top_builddir"; then
+       ac_top_srcdir=.
+    else
+       ac_top_srcdir=`echo $ac_top_builddir | sed 's,/$,,'`
+    fi ;;
+  [\\/]* | ?:[\\/]* )  # Absolute path.
+    ac_srcdir=$srcdir$ac_dir_suffix;
+    ac_top_srcdir=$srcdir ;;
+  *) # Relative path.
+    ac_srcdir=$ac_top_builddir$srcdir$ac_dir_suffix
+    ac_top_srcdir=$ac_top_builddir$srcdir ;;
+esac
+
+# Do not use `cd foo && pwd` to compute absolute paths, because
+# the directories may not exist.
+case `pwd` in
+.) ac_abs_builddir="$ac_dir";;
+*)
+  case "$ac_dir" in
+  .) ac_abs_builddir=`pwd`;;
+  [\\/]* | ?:[\\/]* ) ac_abs_builddir="$ac_dir";;
+  *) ac_abs_builddir=`pwd`/"$ac_dir";;
+  esac;;
+esac
+case $ac_abs_builddir in
+.) ac_abs_top_builddir=${ac_top_builddir}.;;
+*)
+  case ${ac_top_builddir}. in
+  .) ac_abs_top_builddir=$ac_abs_builddir;;
+  [\\/]* | ?:[\\/]* ) ac_abs_top_builddir=${ac_top_builddir}.;;
+  *) ac_abs_top_builddir=$ac_abs_builddir/${ac_top_builddir}.;;
+  esac;;
+esac
+case $ac_abs_builddir in
+.) ac_abs_srcdir=$ac_srcdir;;
+*)
+  case $ac_srcdir in
+  .) ac_abs_srcdir=$ac_abs_builddir;;
+  [\\/]* | ?:[\\/]* ) ac_abs_srcdir=$ac_srcdir;;
+  *) ac_abs_srcdir=$ac_abs_builddir/$ac_srcdir;;
+  esac;;
+esac
+case $ac_abs_builddir in
+.) ac_abs_top_srcdir=$ac_top_srcdir;;
+*)
+  case $ac_top_srcdir in
+  .) ac_abs_top_srcdir=$ac_abs_builddir;;
+  [\\/]* | ?:[\\/]* ) ac_abs_top_srcdir=$ac_top_srcdir;;
+  *) ac_abs_top_srcdir=$ac_abs_builddir/$ac_top_srcdir;;
+  esac;;
+esac
+
+
+  { echo "$as_me:$LINENO: executing $ac_dest commands" >&5
+echo "$as_me: executing $ac_dest commands" >&6;}
+  case $ac_dest in
+    default-1 ) chmod a+x pprintirlog ;;
+  esac
+done
+_ACEOF
 
 cat >>$CONFIG_STATUS <<\_ACEOF
 
@@ -4760,4 +4998,5 @@ if test "$no_create" != yes; then
   # would make configure fail if this is the last instruction.
   $ac_cs_success || { (exit 1); exit 1; }
 fi
+
 
